/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import bd.Conexion;
import bd.AESEncrypt;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.Usuario;
import util.MessageHelper;
import util.MessageType;
import util.Rol;

/**
 *
 * @author ahoihanabi
 */
public class ItnFrmUsuario extends javax.swing.JInternalFrame {
    
    private static ItnFrmUsuario instancia = null;
    private static Conexion conexion;
    private static AESEncrypt crypter;
    private static Mensaje mensaje;
    
    private static ArrayList<Usuario> usuarios;
    
    /**
     * Creates new form intfrmUsuario
     */
    protected ItnFrmUsuario() {
        initComponents();
        
        //Inicializar variables
        conexion = Conexion.getInstancia();
        crypter = new AESEncrypt();
        crypter.addKey("SAI");
        mensaje = new Mensaje();
        
        obtenerUsuarios();
    }
    
    public static ItnFrmUsuario getInstancia() {
        if (instancia == null) {
            instancia = new ItnFrmUsuario();
        }
        return instancia;
    }
    
    public void obtenerUsuarios() {
        try {
            //Para no instanciar los usuarios sin necesidad
            usuarios = usuarios == null ? new ArrayList<>() : usuarios;
            
            String consulta = "SELECT cod_Usuarios, nombre_Usuarios, "
                            + "clave_Usuarios, cod_RolUsuar"
                            + " FROM Usuarios";
            
            conexion.abrirConexion();
            ResultSet result = conexion.ejecutarConsulta(consulta);

            String codUsuario = "", nombreUsuario = "", claveUsuario = "", 
                    codRolUsuario = "";

            while (result.next()) {
                codUsuario = result.getString("cod_Usuarios");
                nombreUsuario = result.getString("nombre_Usuarios");
                claveUsuario = result.getString("clave_Usuarios");
                codRolUsuario = result.getString("cod_RolUsuar");
                
                System.out.println("Codigo: " + codUsuario + 
                                    "\nNombre: " + nombreUsuario + 
                                    "\nClave: " + claveUsuario + 
                                    "\nRol: " + codRolUsuario);
                
                Usuario usuario = new Usuario(nombreUsuario, claveUsuario);
                usuarios.add(usuario);                
            }

        } catch (SQLException ex) {
            System.err.println(ex);
        }
        finally {
            conexion.cerrarConexion();
        }
    }
    
    public boolean crearUsuario(String nombre, String contra, Rol rol) {
        
        //Código de rol de usuario. 1: Administrador, 2: Estándar
        int codRol = rol.equals(Rol.Administrador) ? 1 : 2;
        contra = crypter.encriptar(contra);
        
        boolean res = false;
        try {
            String consulta = "INSERT INTO `Usuarios`(`cod_Usuarios`, "
                    + "`nombre_Usuarios`, `clave_Usuarios`, `cod_RolUsuar`) "
                    + "VALUES (NULL, '" + nombre + "', '" + contra + "', " + codRol + ")";
            
            conexion.abrirConexion();
            res = conexion.ejecutarActualizar(consulta) != -1;

        } catch (SQLException ex) {
            System.err.println(ex);
        }
        finally {
            conexion.cerrarConexion();
        }
        return res;
    }
    
//    private void mostrarMensaje(MessageType tipo, MessageHelper msg) {
//        
//        int pan;
//        
//        switch (tipo) {
//            case INFORMATION:
//                pan = JOptionPane.INFORMATION_MESSAGE;
//                break;
//            case WARNING:
//                pan = JOptionPane.WARNING_MESSAGE;
//                break;
//            case ERROR:
//                pan = JOptionPane.ERROR_MESSAGE;
//                break;
//            default:
//                pan = JOptionPane.INFORMATION_MESSAGE;
//                break;
//        }
//        
//        JOptionPane.showMessageDialog(null, mensaje.obtenerMensaje(msg), tipo.toString(), pan);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        bg_crear_rol = new javax.swing.ButtonGroup();
        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("sai_aes?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        usuarios_1Query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT u FROM Usuarios_1 u");
        usuarios_1List = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : usuarios_1Query.getResultList();
        pnl_modUsuario = new javax.swing.JPanel();
        tb_modUsuario_permisos = new javax.swing.JTabbedPane();
        pnl_listado = new javax.swing.JPanel();
        lbl_listado_buscarUsuario = new javax.swing.JLabel();
        txt_listado_buscar = new javax.swing.JTextField();
        scpnl_tbl_usuarioListado = new javax.swing.JScrollPane();
        tbl_usuarioListado = new javax.swing.JTable();
        pnl_crear = new javax.swing.JPanel();
        txt_crear_nombreUsuario = new javax.swing.JTextField();
        lbl_crear_nombreUsuario = new javax.swing.JLabel();
        lbl_crear_password = new javax.swing.JLabel();
        lbl_crear_confirmPassw = new javax.swing.JLabel();
        pw_crear_contra = new javax.swing.JPasswordField();
        pw_crear_confContra = new javax.swing.JPasswordField();
        btn_crearUsuario = new javax.swing.JButton();
        scpnl_tbl_usuarioCreado = new javax.swing.JScrollPane();
        tbl_usuarioCreado = new javax.swing.JTable();
        pnl_crear_rolContainer = new javax.swing.JPanel();
        rb_crear_rolEstandar = new javax.swing.JRadioButton();
        rb_crear_rolAdmin = new javax.swing.JRadioButton();
        pnl_actualizar = new javax.swing.JPanel();
        lbl_actuali_nombreUsuario = new javax.swing.JLabel();
        txt_actuali_nombreUsuario = new javax.swing.JTextField();
        lbl_actuali_passActual = new javax.swing.JLabel();
        btn_actualiUsuario = new javax.swing.JButton();
        lbl_actuali_passNew = new javax.swing.JLabel();
        pw_actuali_newPass = new javax.swing.JPasswordField();
        pw_actuali_confNewPass = new javax.swing.JPasswordField();
        pnl_deshabilitar = new javax.swing.JPanel();
        scpnl_tbl_usuarioDeshab = new javax.swing.JScrollPane();
        tbl_deshabilitar = new javax.swing.JTable();
        lbl_deshab_selectUsuario = new javax.swing.JLabel();
        pnl_crear_rolContainer1 = new javax.swing.JPanel();
        rb_deshab_deshabilitar = new javax.swing.JRadioButton();
        rb_deshab_habilitar = new javax.swing.JRadioButton();
        btn_deshabilitar = new javax.swing.JButton();
        pnl_actualizarPermisos = new javax.swing.JPanel();
        lbl_actPermi_selectUsuario = new javax.swing.JLabel();
        pnl_actPermi_rolContainer = new javax.swing.JPanel();
        rb_actPermi_estandar = new javax.swing.JRadioButton();
        rb_actPermi_Admin = new javax.swing.JRadioButton();
        btn_actPermi = new javax.swing.JButton();
        scpnl_tbl_usuarioActPermiso = new javax.swing.JScrollPane();
        tbl_actPermisos = new javax.swing.JTable();

        pnl_modUsuario.setPreferredSize(new java.awt.Dimension(1239, 680));

        lbl_listado_buscarUsuario.setText("Buscar usuario: ");

        scpnl_tbl_usuarioListado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scpnl_tbl_usuarioListadoMouseClicked(evt);
            }
        });

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, usuarios_1List, tbl_usuarioListado);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codUsuarios}"));
        columnBinding.setColumnName("Cod Usuarios");
        columnBinding.setColumnClass(Long.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nombreUsuarios}"));
        columnBinding.setColumnName("Nombre Usuarios");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${claveUsuarios}"));
        columnBinding.setColumnName("Clave Usuarios");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codRolUsuar}"));
        columnBinding.setColumnName("Cod Rol Usuar");
        columnBinding.setColumnClass(Long.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        tbl_usuarioListado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_usuarioListadoMouseClicked(evt);
            }
        });
        scpnl_tbl_usuarioListado.setViewportView(tbl_usuarioListado);

        javax.swing.GroupLayout pnl_listadoLayout = new javax.swing.GroupLayout(pnl_listado);
        pnl_listado.setLayout(pnl_listadoLayout);
        pnl_listadoLayout.setHorizontalGroup(
            pnl_listadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_listadoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnl_listadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scpnl_tbl_usuarioListado, javax.swing.GroupLayout.PREFERRED_SIZE, 1073, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_listadoLayout.createSequentialGroup()
                        .addComponent(lbl_listado_buscarUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_listado_buscar)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        pnl_listadoLayout.setVerticalGroup(
            pnl_listadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_listadoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pnl_listadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_listado_buscarUsuario)
                    .addComponent(txt_listado_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(scpnl_tbl_usuarioListado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        tb_modUsuario_permisos.addTab("Listado Usuarios", pnl_listado);

        lbl_crear_nombreUsuario.setText("Nombre de Usuario:");

        lbl_crear_password.setText("Contraseña:");

        lbl_crear_confirmPassw.setText("Confirmar Contraseña:");

        btn_crearUsuario.setText("Crear Usuario");
        btn_crearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearUsuarioActionPerformed(evt);
            }
        });

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, usuarios_1List, tbl_usuarioCreado);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codUsuarios}"));
        columnBinding.setColumnName("Cod Usuarios");
        columnBinding.setColumnClass(Long.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nombreUsuarios}"));
        columnBinding.setColumnName("Nombre Usuarios");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${claveUsuarios}"));
        columnBinding.setColumnName("Clave Usuarios");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codRolUsuar}"));
        columnBinding.setColumnName("Cod Rol Usuar");
        columnBinding.setColumnClass(Long.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        tbl_usuarioCreado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_usuarioCreadoMouseClicked(evt);
            }
        });
        scpnl_tbl_usuarioCreado.setViewportView(tbl_usuarioCreado);

        pnl_crear_rolContainer.setBorder(javax.swing.BorderFactory.createTitledBorder("Rol de Usuarios:"));

        bg_crear_rol.add(rb_crear_rolEstandar);
        rb_crear_rolEstandar.setText("Estándar");

        bg_crear_rol.add(rb_crear_rolAdmin);
        rb_crear_rolAdmin.setText("Administrador");

        javax.swing.GroupLayout pnl_crear_rolContainerLayout = new javax.swing.GroupLayout(pnl_crear_rolContainer);
        pnl_crear_rolContainer.setLayout(pnl_crear_rolContainerLayout);
        pnl_crear_rolContainerLayout.setHorizontalGroup(
            pnl_crear_rolContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_crear_rolContainerLayout.createSequentialGroup()
                .addComponent(rb_crear_rolAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(rb_crear_rolEstandar)
                .addContainerGap())
        );
        pnl_crear_rolContainerLayout.setVerticalGroup(
            pnl_crear_rolContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_crear_rolContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_crear_rolContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_crear_rolAdmin)
                    .addComponent(rb_crear_rolEstandar)))
        );

        javax.swing.GroupLayout pnl_crearLayout = new javax.swing.GroupLayout(pnl_crear);
        pnl_crear.setLayout(pnl_crearLayout);
        pnl_crearLayout.setHorizontalGroup(
            pnl_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_crearLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pnl_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scpnl_tbl_usuarioCreado)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_crearLayout.createSequentialGroup()
                        .addGroup(pnl_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_crear_nombreUsuario)
                            .addComponent(pnl_crear_rolContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_crear_nombreUsuario))
                        .addGap(179, 179, 179)
                        .addGroup(pnl_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_crearLayout.createSequentialGroup()
                                .addGroup(pnl_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pw_crear_confContra, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pw_crear_contra, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_crear_confirmPassw))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                                .addComponent(btn_crearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_crearLayout.createSequentialGroup()
                                .addComponent(lbl_crear_password)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(72, 72, 72))
        );
        pnl_crearLayout.setVerticalGroup(
            pnl_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_crearLayout.createSequentialGroup()
                .addGroup(pnl_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_crearLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(btn_crearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_crearLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(pnl_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_crear_nombreUsuario)
                            .addComponent(lbl_crear_password))
                        .addGap(14, 14, 14)
                        .addGroup(pnl_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_crear_nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pw_crear_contra, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_crearLayout.createSequentialGroup()
                                .addComponent(lbl_crear_confirmPassw)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pw_crear_confContra, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pnl_crear_rolContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37)
                .addComponent(scpnl_tbl_usuarioCreado, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        tb_modUsuario_permisos.addTab("Crear", pnl_crear);

        lbl_actuali_nombreUsuario.setText("Nombre de Usuario:");

        lbl_actuali_passActual.setText("Nueva Contraseña:");

        btn_actualiUsuario.setText("Guardar Cambios");
        btn_actualiUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualiUsuarioActionPerformed(evt);
            }
        });

        lbl_actuali_passNew.setText("Confirmar Contraseña:");

        pw_actuali_newPass.setText("jPasswordField1");

        pw_actuali_confNewPass.setText("jPasswordField1");

        javax.swing.GroupLayout pnl_actualizarLayout = new javax.swing.GroupLayout(pnl_actualizar);
        pnl_actualizar.setLayout(pnl_actualizarLayout);
        pnl_actualizarLayout.setHorizontalGroup(
            pnl_actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_actualizarLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(pnl_actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_actuali_nombreUsuario)
                    .addComponent(txt_actuali_nombreUsuario)
                    .addComponent(btn_actualiUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 322, Short.MAX_VALUE)
                .addGroup(pnl_actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_actuali_passActual)
                    .addComponent(pw_actuali_confNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_actuali_passNew)
                    .addComponent(pw_actuali_newPass, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(193, 193, 193))
        );
        pnl_actualizarLayout.setVerticalGroup(
            pnl_actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_actualizarLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(pnl_actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_actualizarLayout.createSequentialGroup()
                        .addGroup(pnl_actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_actuali_nombreUsuario)
                            .addComponent(lbl_actuali_passActual))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl_actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_actuali_nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pw_actuali_newPass, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(btn_actualiUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_actualizarLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(lbl_actuali_passNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pw_actuali_confNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(389, Short.MAX_VALUE))
        );

        tb_modUsuario_permisos.addTab("Actualizar", pnl_actualizar);

        tbl_deshabilitar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scpnl_tbl_usuarioDeshab.setViewportView(tbl_deshabilitar);

        lbl_deshab_selectUsuario.setText("Seleccionar Usuario:");

        pnl_crear_rolContainer1.setBorder(javax.swing.BorderFactory.createTitledBorder("Activo:"));

        bg_crear_rol.add(rb_deshab_deshabilitar);
        rb_deshab_deshabilitar.setText("Deshabilitar");

        bg_crear_rol.add(rb_deshab_habilitar);
        rb_deshab_habilitar.setText("Habilitar");

        javax.swing.GroupLayout pnl_crear_rolContainer1Layout = new javax.swing.GroupLayout(pnl_crear_rolContainer1);
        pnl_crear_rolContainer1.setLayout(pnl_crear_rolContainer1Layout);
        pnl_crear_rolContainer1Layout.setHorizontalGroup(
            pnl_crear_rolContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_crear_rolContainer1Layout.createSequentialGroup()
                .addComponent(rb_deshab_habilitar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(rb_deshab_deshabilitar)
                .addContainerGap())
        );
        pnl_crear_rolContainer1Layout.setVerticalGroup(
            pnl_crear_rolContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_crear_rolContainer1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_crear_rolContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_deshab_habilitar)
                    .addComponent(rb_deshab_deshabilitar)))
        );

        btn_deshabilitar.setText("Guardar Cambios");

        javax.swing.GroupLayout pnl_deshabilitarLayout = new javax.swing.GroupLayout(pnl_deshabilitar);
        pnl_deshabilitar.setLayout(pnl_deshabilitarLayout);
        pnl_deshabilitarLayout.setHorizontalGroup(
            pnl_deshabilitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_deshabilitarLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnl_deshabilitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_deshabilitarLayout.createSequentialGroup()
                        .addComponent(pnl_crear_rolContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(565, 565, 565)
                        .addComponent(btn_deshabilitar, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_deshabilitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_deshab_selectUsuario)
                        .addComponent(scpnl_tbl_usuarioDeshab, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        pnl_deshabilitarLayout.setVerticalGroup(
            pnl_deshabilitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_deshabilitarLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lbl_deshab_selectUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scpnl_tbl_usuarioDeshab, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(pnl_deshabilitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnl_crear_rolContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_deshabilitar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        tb_modUsuario_permisos.addTab("Deshabilitar", pnl_deshabilitar);

        lbl_actPermi_selectUsuario.setText("Seleccionar Usuario:");

        pnl_actPermi_rolContainer.setBorder(javax.swing.BorderFactory.createTitledBorder("Rol Usuario:"));

        bg_crear_rol.add(rb_actPermi_estandar);
        rb_actPermi_estandar.setText("Estándar");

        bg_crear_rol.add(rb_actPermi_Admin);
        rb_actPermi_Admin.setText("Administrador");

        javax.swing.GroupLayout pnl_actPermi_rolContainerLayout = new javax.swing.GroupLayout(pnl_actPermi_rolContainer);
        pnl_actPermi_rolContainer.setLayout(pnl_actPermi_rolContainerLayout);
        pnl_actPermi_rolContainerLayout.setHorizontalGroup(
            pnl_actPermi_rolContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_actPermi_rolContainerLayout.createSequentialGroup()
                .addComponent(rb_actPermi_Admin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(rb_actPermi_estandar)
                .addContainerGap())
        );
        pnl_actPermi_rolContainerLayout.setVerticalGroup(
            pnl_actPermi_rolContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_actPermi_rolContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_actPermi_rolContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_actPermi_Admin)
                    .addComponent(rb_actPermi_estandar)))
        );

        btn_actPermi.setText("Guardar Cambios");

        tbl_actPermisos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scpnl_tbl_usuarioActPermiso.setViewportView(tbl_actPermisos);

        javax.swing.GroupLayout pnl_actualizarPermisosLayout = new javax.swing.GroupLayout(pnl_actualizarPermisos);
        pnl_actualizarPermisos.setLayout(pnl_actualizarPermisosLayout);
        pnl_actualizarPermisosLayout.setHorizontalGroup(
            pnl_actualizarPermisosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_actualizarPermisosLayout.createSequentialGroup()
                .addGroup(pnl_actualizarPermisosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_actualizarPermisosLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(pnl_actPermi_rolContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(559, 559, 559)
                        .addComponent(btn_actPermi, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_actualizarPermisosLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(pnl_actualizarPermisosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_actPermi_selectUsuario)
                            .addComponent(scpnl_tbl_usuarioActPermiso, javax.swing.GroupLayout.PREFERRED_SIZE, 1040, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        pnl_actualizarPermisosLayout.setVerticalGroup(
            pnl_actualizarPermisosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_actualizarPermisosLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lbl_actPermi_selectUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scpnl_tbl_usuarioActPermiso, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(pnl_actualizarPermisosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnl_actPermi_rolContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_actPermi, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        tb_modUsuario_permisos.addTab("Actualizar permisos", pnl_actualizarPermisos);

        javax.swing.GroupLayout pnl_modUsuarioLayout = new javax.swing.GroupLayout(pnl_modUsuario);
        pnl_modUsuario.setLayout(pnl_modUsuarioLayout);
        pnl_modUsuarioLayout.setHorizontalGroup(
            pnl_modUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_modUsuarioLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(tb_modUsuario_permisos)
                .addContainerGap())
        );
        pnl_modUsuarioLayout.setVerticalGroup(
            pnl_modUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_modUsuarioLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(tb_modUsuario_permisos, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_modUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 1194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_modUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_crearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearUsuarioActionPerformed
        
        Mensaje msg = new Mensaje();
        
        String nombre =  txt_crear_nombreUsuario.getText();
        String contra =  new String(pw_crear_contra.getPassword());
        String contraConf =  new String(pw_crear_confContra.getPassword());
        //Si el radio button rol Estándar está seleccionado
        Rol rol = rb_crear_rolEstandar.isSelected() ? Rol.Estándar : Rol.Administrador;
        
        if (!nombre.isEmpty()) {
            if (!contra.isEmpty()) {
                if (contra.equals(contraConf)) {
                    if (crearUsuario(nombre, contra, rol)) {
                        //obtenerUsuarios();
                        msg.mostrarMensaje(MessageType.INFORMATION, MessageHelper.USER_INSERTION_SUCCESS);
                    } else {
                        msg.mostrarMensaje(MessageType.ERROR, MessageHelper.USER_INSERTION_FAILURE);
                    }
                } else {
                    msg.mostrarMensaje(MessageType.WARNING, MessageHelper.MISMATCHING_PASSWORD_FIELDS);
                }
            } else {
                msg.mostrarMensaje(MessageType.WARNING, MessageHelper.EMPTY_PASSWORD_FIELD);
            }
        } else {
            msg.mostrarMensaje(MessageType.WARNING, MessageHelper.EMPTY_USERNAME_FIELD);
        }
    }//GEN-LAST:event_btn_crearUsuarioActionPerformed

    private void tbl_usuarioCreadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_usuarioCreadoMouseClicked
        
        
    }//GEN-LAST:event_tbl_usuarioCreadoMouseClicked

    private void btn_actualiUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualiUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_actualiUsuarioActionPerformed

    private void scpnl_tbl_usuarioListadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scpnl_tbl_usuarioListadoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_scpnl_tbl_usuarioListadoMouseClicked

    private void tbl_usuarioListadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_usuarioListadoMouseClicked
        
        //DefaultTableModel model = (DefaultTableModel)tbl_usuarioCreado.getModel();
        //int selectedRowIndex = tbl_usuarioCreado.getSelectedRow();
        //System.out.print(selectedRowIndex);
        
        //txt_listado_buscar.setText(model.getValueAt(selectedRowIndex,1).toString());
    }//GEN-LAST:event_tbl_usuarioListadoMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_crear_rol;
    private javax.swing.JButton btn_actPermi;
    private javax.swing.JButton btn_actualiUsuario;
    private javax.swing.JButton btn_crearUsuario;
    private javax.swing.JButton btn_deshabilitar;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel lbl_actPermi_selectUsuario;
    private javax.swing.JLabel lbl_actuali_nombreUsuario;
    private javax.swing.JLabel lbl_actuali_passActual;
    private javax.swing.JLabel lbl_actuali_passNew;
    private javax.swing.JLabel lbl_crear_confirmPassw;
    private javax.swing.JLabel lbl_crear_nombreUsuario;
    private javax.swing.JLabel lbl_crear_password;
    private javax.swing.JLabel lbl_deshab_selectUsuario;
    private javax.swing.JLabel lbl_listado_buscarUsuario;
    private javax.swing.JPanel pnl_actPermi_rolContainer;
    private javax.swing.JPanel pnl_actualizar;
    private javax.swing.JPanel pnl_actualizarPermisos;
    private javax.swing.JPanel pnl_crear;
    private javax.swing.JPanel pnl_crear_rolContainer;
    private javax.swing.JPanel pnl_crear_rolContainer1;
    private javax.swing.JPanel pnl_deshabilitar;
    private javax.swing.JPanel pnl_listado;
    private javax.swing.JPanel pnl_modUsuario;
    private javax.swing.JPasswordField pw_actuali_confNewPass;
    private javax.swing.JPasswordField pw_actuali_newPass;
    private javax.swing.JPasswordField pw_crear_confContra;
    private javax.swing.JPasswordField pw_crear_contra;
    private javax.swing.JRadioButton rb_actPermi_Admin;
    private javax.swing.JRadioButton rb_actPermi_estandar;
    private javax.swing.JRadioButton rb_crear_rolAdmin;
    private javax.swing.JRadioButton rb_crear_rolEstandar;
    private javax.swing.JRadioButton rb_deshab_deshabilitar;
    private javax.swing.JRadioButton rb_deshab_habilitar;
    private javax.swing.JScrollPane scpnl_tbl_usuarioActPermiso;
    private javax.swing.JScrollPane scpnl_tbl_usuarioCreado;
    private javax.swing.JScrollPane scpnl_tbl_usuarioDeshab;
    private javax.swing.JScrollPane scpnl_tbl_usuarioListado;
    private javax.swing.JTabbedPane tb_modUsuario_permisos;
    private javax.swing.JTable tbl_actPermisos;
    private javax.swing.JTable tbl_deshabilitar;
    private javax.swing.JTable tbl_usuarioCreado;
    private javax.swing.JTable tbl_usuarioListado;
    private javax.swing.JTextField txt_actuali_nombreUsuario;
    private javax.swing.JTextField txt_crear_nombreUsuario;
    private javax.swing.JTextField txt_listado_buscar;
    private java.util.List<presentacion.Usuarios_1> usuarios_1List;
    private javax.persistence.Query usuarios_1Query;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}