/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import controladores.CtrImpuesto;
import javax.swing.JOptionPane;
import logica.negocio.Impuesto;
import logica.servicios.Mensaje;
import util.TipoMensaje;

/**
 * Inicializa la ventana de dialog que contiene la información de exoneraciones.
 * @author aoihanabi
 */
public class DlgFacImpuesto extends javax.swing.JDialog {

    public static ItnFrmFacturacion ifrmFacturacion;
    private static DlgFacExoneracion dialogExoneracion;
    private static CtrImpuesto controlador;
    public static Impuesto impuesto;
    private static Mensaje msg;

    /**
     * Creates new form DlgFacImpuesto.
     * @param parent ventana padre de este Jdialog
     * @param modal establece si la ventana permite acceso a otras mientras está
     * abierta.
     */
    public DlgFacImpuesto(ItnFrmFacturacion parent /*java.awt.Frame parent*/,
            boolean modal) {
        //super(parent, modal);
        this.ifrmFacturacion = parent;
        this.setModal(modal);
        initComponents();
        setLocationRelativeTo(this);
        msg = new Mensaje();
        controlador = new CtrImpuesto();
    }
    /**
     * 
     * @return 
     */
    public double getPrecio() {
        return ifrmFacturacion.getPrecioSinImpuesto();
    }
    /**
     * 
     * @return 
     */
    public double getValorImpuesto() {
        double porcentajeImpuesto;
        double valorImpuesto = 0.0;
        try{
            if(!txtImpuesto.getText().isEmpty()) {
                porcentajeImpuesto = Double.valueOf(txtImpuesto.getText())/100;
                valorImpuesto = getPrecio() * porcentajeImpuesto;
                
            } else {
                msg.mostrarMensaje(JOptionPane.INFORMATION_MESSAGE, 
                        TipoMensaje.EMPTY_TEXT_FIELD);
            }
        } catch (NumberFormatException ex) {
            msg.mostrarMensaje(JOptionPane.INFORMATION_MESSAGE, 
                    TipoMensaje.WRONG_DECIMAL_NUMBER);
            System.out.println("Number exception: " + ex);
        } catch (Exception ex) {
            msg.mostrarMensaje(JOptionPane.INFORMATION_MESSAGE,
                    TipoMensaje.SOMETHING_WENT_WRONG);
            System.out.println("Exception: " + ex);
        } finally {
            return valorImpuesto;
        }
    }

    /**
     * 
     * @return 
     */
    public String codImpuestosHac() {
        String codigo = "98";
        if(rbGeneralVentas.isSelected()) {
            codigo = "01";
        } else if(rbServicio.isSelected()) {
            codigo = "07";
        }
        return codigo;
    }
    /**
     * 
     */
    public void enviarDatos() {
        if(!txtImpuesto.getText().isEmpty()) {
            if(getValorImpuesto() > 0.0) {
                ifrmFacturacion.montoImpuesto = getValorImpuesto();
                controlador.crearImpuesto(codImpuestosHac(), 
                        Double.valueOf(txtImpuesto.getText())/100, 
                        getValorImpuesto());
                this.dispose();
            } else {
                msg.mostrarMensaje(JOptionPane.INFORMATION_MESSAGE, 
                    TipoMensaje.TAX_MISSING);
            }
        } else {
            msg.mostrarMensaje(JOptionPane.INFORMATION_MESSAGE, 
                    TipoMensaje.EMPTY_TEXT_FIELD);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgTipoImpuesto = new javax.swing.ButtonGroup();
        pnlPrincipal = new javax.swing.JPanel();
        pnlImpuesto = new javax.swing.JPanel();
        pnlTipoImpuesto = new javax.swing.JPanel();
        rbGeneralVentas = new javax.swing.JRadioButton();
        rbServicio = new javax.swing.JRadioButton();
        rbOtro = new javax.swing.JRadioButton();
        txtImpuesto = new javax.swing.JTextField();
        lblMontoImpuesto = new javax.swing.JLabel();
        lblTextTarifaImpuesto = new javax.swing.JLabel();
        lblTextMontoImpuesto = new javax.swing.JLabel();
        lblTextMontoImpuesto1 = new javax.swing.JLabel();
        pnlExoneracion = new javax.swing.JPanel();
        pnlTipoExoneracion = new javax.swing.JPanel();
        rbCompraAutorizada = new javax.swing.JRadioButton();
        rbVentaDiplomatico = new javax.swing.JRadioButton();
        rbOrdenCompra = new javax.swing.JRadioButton();
        rbExencionesHacienda = new javax.swing.JRadioButton();
        rbZonaFranca = new javax.swing.JRadioButton();
        rbOtros = new javax.swing.JRadioButton();
        lblTextMontoImpuestoEx = new javax.swing.JLabel();
        lblTextPorcentCompra = new javax.swing.JLabel();
        txtPorcentajeCompra = new javax.swing.JTextField();
        lblMontoImpuestoEx = new javax.swing.JLabel();
        ckbExonerar = new javax.swing.JCheckBox();
        btnAceptarImpEx = new javax.swing.JButton();
        btnCancelarImpEx = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar impuesto");

        pnlImpuesto.setBorder(javax.swing.BorderFactory.createTitledBorder("Impuesto:"));

        pnlTipoImpuesto.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de impuesto:"));

        bgTipoImpuesto.add(rbGeneralVentas);
        rbGeneralVentas.setText("General sobre ventas");

        bgTipoImpuesto.add(rbServicio);
        rbServicio.setText("Servicio");

        bgTipoImpuesto.add(rbOtro);
        rbOtro.setSelected(true);
        rbOtro.setText("Otros");

        javax.swing.GroupLayout pnlTipoImpuestoLayout = new javax.swing.GroupLayout(pnlTipoImpuesto);
        pnlTipoImpuesto.setLayout(pnlTipoImpuestoLayout);
        pnlTipoImpuestoLayout.setHorizontalGroup(
            pnlTipoImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTipoImpuestoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTipoImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbOtro)
                    .addComponent(rbServicio)
                    .addComponent(rbGeneralVentas))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        pnlTipoImpuestoLayout.setVerticalGroup(
            pnlTipoImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTipoImpuestoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbGeneralVentas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbServicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbOtro)
                .addGap(26, 26, 26))
        );

        txtImpuesto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtImpuestoKeyReleased(evt);
            }
        });

        lblMontoImpuesto.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.activeCaption));

        lblTextTarifaImpuesto.setText("Impuesto: ");

        lblTextMontoImpuesto.setText("Monto:");

        lblTextMontoImpuesto1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTextMontoImpuesto1.setText("%");

        javax.swing.GroupLayout pnlImpuestoLayout = new javax.swing.GroupLayout(pnlImpuesto);
        pnlImpuesto.setLayout(pnlImpuestoLayout);
        pnlImpuestoLayout.setHorizontalGroup(
            pnlImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImpuestoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlTipoImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlImpuestoLayout.createSequentialGroup()
                        .addGroup(pnlImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTextTarifaImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTextMontoImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlImpuestoLayout.createSequentialGroup()
                                .addComponent(txtImpuesto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTextMontoImpuesto1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblMontoImpuesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        pnlImpuestoLayout.setVerticalGroup(
            pnlImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImpuestoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTipoImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTextTarifaImpuesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTextMontoImpuesto1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTextMontoImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMontoImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pnlExoneracion.setBorder(javax.swing.BorderFactory.createTitledBorder("Exoneración:"));
        pnlExoneracion.setEnabled(false);

        pnlTipoExoneracion.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccione el tipo de exoneración:"));
        pnlTipoExoneracion.setEnabled(false);

        rbCompraAutorizada.setSelected(true);
        rbCompraAutorizada.setText("Compras autorizadas");
        rbCompraAutorizada.setEnabled(false);

        rbVentaDiplomatico.setText("Ventas exentas a diplomáticos");
        rbVentaDiplomatico.setEnabled(false);

        rbOrdenCompra.setText("Orden de compra (Instituciones públicas y otros)");
        rbOrdenCompra.setEnabled(false);

        rbExencionesHacienda.setText("Exenciones Dirección General de Hacienda");
        rbExencionesHacienda.setEnabled(false);

        rbZonaFranca.setText("Zonas Francas");
        rbZonaFranca.setEnabled(false);

        rbOtros.setText("Otros");
        rbOtros.setEnabled(false);

        javax.swing.GroupLayout pnlTipoExoneracionLayout = new javax.swing.GroupLayout(pnlTipoExoneracion);
        pnlTipoExoneracion.setLayout(pnlTipoExoneracionLayout);
        pnlTipoExoneracionLayout.setHorizontalGroup(
            pnlTipoExoneracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTipoExoneracionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTipoExoneracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTipoExoneracionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlTipoExoneracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbOrdenCompra)
                            .addComponent(rbVentaDiplomatico)
                            .addComponent(rbCompraAutorizada)
                            .addComponent(rbExencionesHacienda)))
                    .addGroup(pnlTipoExoneracionLayout.createSequentialGroup()
                        .addGroup(pnlTipoExoneracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbZonaFranca)
                            .addComponent(rbOtros))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlTipoExoneracionLayout.setVerticalGroup(
            pnlTipoExoneracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTipoExoneracionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbCompraAutorizada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbVentaDiplomatico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbOrdenCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbExencionesHacienda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbZonaFranca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbOtros))
        );

        lblTextMontoImpuestoEx.setText("Monto Impuesto:");
        lblTextMontoImpuestoEx.setEnabled(false);
        lblTextMontoImpuestoEx.setOpaque(true);

        lblTextPorcentCompra.setText("Porcentaje Compra:");
        lblTextPorcentCompra.setToolTipText("");
        lblTextPorcentCompra.setEnabled(false);
        lblTextPorcentCompra.setOpaque(true);

        txtPorcentajeCompra.setEnabled(false);

        lblMontoImpuestoEx.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.activeCaption));
        lblMontoImpuestoEx.setEnabled(false);
        lblMontoImpuestoEx.setOpaque(true);

        javax.swing.GroupLayout pnlExoneracionLayout = new javax.swing.GroupLayout(pnlExoneracion);
        pnlExoneracion.setLayout(pnlExoneracionLayout);
        pnlExoneracionLayout.setHorizontalGroup(
            pnlExoneracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExoneracionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlExoneracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTipoExoneracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlExoneracionLayout.createSequentialGroup()
                        .addGroup(pnlExoneracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTextMontoImpuestoEx, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTextPorcentCompra))
                        .addGap(18, 18, 18)
                        .addGroup(pnlExoneracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMontoImpuestoEx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPorcentajeCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlExoneracionLayout.setVerticalGroup(
            pnlExoneracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExoneracionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTipoExoneracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlExoneracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlExoneracionLayout.createSequentialGroup()
                        .addComponent(lblTextMontoImpuestoEx, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTextPorcentCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlExoneracionLayout.createSequentialGroup()
                        .addComponent(lblMontoImpuestoEx, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPorcentajeCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        ckbExonerar.setText("Exonerar");

        btnAceptarImpEx.setText("Aceptar");
        btnAceptarImpEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarImpExActionPerformed(evt);
            }
        });

        btnCancelarImpEx.setText("Cancelar");
        btnCancelarImpEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarImpExActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(btnCancelarImpEx, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAceptarImpEx, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ckbExonerar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(pnlImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlExoneracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlExoneracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbExonerar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarImpEx, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarImpEx, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarImpExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarImpExActionPerformed
        
        this.dispose();
    }//GEN-LAST:event_btnCancelarImpExActionPerformed

    private void btnAceptarImpExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarImpExActionPerformed
        enviarDatos();
    }//GEN-LAST:event_btnAceptarImpExActionPerformed

    private void txtImpuestoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImpuestoKeyReleased
        //String porcentaje = txtImpuesto.getText();
        double valor = 0;
        try {
            valor = getValorImpuesto();
        } catch (NumberFormatException ex) {
            msg.mostrarMensaje(JOptionPane.INFORMATION_MESSAGE, TipoMensaje.WRONG_DECIMAL_NUMBER);
            System.out.println("Number exception: " + ex);
        }
        lblMontoImpuesto.setText(String.valueOf(valor));
    }//GEN-LAST:event_txtImpuestoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgFacImpuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgFacImpuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgFacImpuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgFacImpuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgFacImpuesto dialog = new DlgFacImpuesto(ifrmFacturacion, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgTipoImpuesto;
    private javax.swing.JButton btnAceptarImpEx;
    private javax.swing.JButton btnCancelarImpEx;
    private javax.swing.JCheckBox ckbExonerar;
    private javax.swing.JLabel lblMontoImpuesto;
    private javax.swing.JLabel lblMontoImpuestoEx;
    private javax.swing.JLabel lblTextMontoImpuesto;
    private javax.swing.JLabel lblTextMontoImpuesto1;
    private javax.swing.JLabel lblTextMontoImpuestoEx;
    private javax.swing.JLabel lblTextPorcentCompra;
    private javax.swing.JLabel lblTextTarifaImpuesto;
    private javax.swing.JPanel pnlExoneracion;
    private javax.swing.JPanel pnlImpuesto;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlTipoExoneracion;
    private javax.swing.JPanel pnlTipoImpuesto;
    private javax.swing.JRadioButton rbCompraAutorizada;
    private javax.swing.JRadioButton rbExencionesHacienda;
    private javax.swing.JRadioButton rbGeneralVentas;
    private javax.swing.JRadioButton rbOrdenCompra;
    private javax.swing.JRadioButton rbOtro;
    private javax.swing.JRadioButton rbOtros;
    private javax.swing.JRadioButton rbServicio;
    private javax.swing.JRadioButton rbVentaDiplomatico;
    private javax.swing.JRadioButton rbZonaFranca;
    private javax.swing.JTextField txtImpuesto;
    private javax.swing.JTextField txtPorcentajeCompra;
    // End of variables declaration//GEN-END:variables
}
