/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import controladores.CtrImpuesto;
import javax.swing.JOptionPane;
import logica.negocio.Impuesto;
import logica.servicios.Mensaje;
import util.TipoMensaje;

/**
 * Inicializa la ventana de dialog que contiene la información de exoneraciones.
 * @author aoihanabi
 */
public class DlgFacImpuesto extends javax.swing.JDialog {

    public static ItnFrmFacturacion ifrmFacturacion;
    private static DlgFacExoneracion dialogExoneracion;
    private static CtrImpuesto controlador;
    public static Impuesto impuesto;
    private static Mensaje msg;

    /**
     * Creates new form DlgFacImpuesto.
     * @param parent ventana padre de este Jdialog
     * @param modal establece si la ventana permite acceso a otras mientras está
     * abierta.
     */
    public DlgFacImpuesto(ItnFrmFacturacion parent /*java.awt.Frame parent*/,
            boolean modal) {
        //super(parent, modal);
        this.ifrmFacturacion = parent;
        this.setModal(modal);
        initComponents();
        setLocationRelativeTo(this);
        msg = new Mensaje();
        controlador = new CtrImpuesto();
    }
    /**
     * 
     * @return 
     */
    public double getPrecio() {
        return ifrmFacturacion.getPrecioSinImpuesto();
    }
    /**
     * 
     * @return 
     */
    public double getValorImpuesto() {
        double porcentajeImpuesto;
        double valorImpuesto = 0.0;
        try{
            if(!txtImpuesto.getText().isEmpty()) {
                porcentajeImpuesto = Double.valueOf(txtImpuesto.getText())/100;
                valorImpuesto = getPrecio() * porcentajeImpuesto;
                
            } else {
                msg.mostrarMensaje(JOptionPane.INFORMATION_MESSAGE, 
                        TipoMensaje.EMPTY_TEXT_FIELD);
            }
        } catch (NumberFormatException ex) {
            msg.mostrarMensaje(JOptionPane.INFORMATION_MESSAGE, 
                    TipoMensaje.WRONG_DECIMAL_NUMBER);
            System.out.println("Number exception: " + ex);
        } catch (Exception ex) {
            msg.mostrarMensaje(JOptionPane.INFORMATION_MESSAGE,
                    TipoMensaje.SOMETHING_WENT_WRONG);
            System.out.println("Exception: " + ex);
        } finally {
            return valorImpuesto;
        }
    }

    /**
     * 
     * @return 
     */
    public String codImpuestosHac() {
        String codigo = "98";
        if(rbGeneralVentas.isSelected()) {
            codigo = "01";
        } else if(rbServicio.isSelected()) {
            codigo = "07";
        }
        return codigo;
    }
    /**
     * 
     */
    public void enviarDatos() {
        if(!txtImpuesto.getText().isEmpty()) {
            if(getValorImpuesto() > 0.0) {
                ifrmFacturacion.montoImpuesto = getValorImpuesto();
                controlador.crearImpuesto(codImpuestosHac(), 
                        Double.valueOf(txtImpuesto.getText())/100, 
                        getValorImpuesto());
                this.dispose();
            } else {
                msg.mostrarMensaje(JOptionPane.INFORMATION_MESSAGE, 
                    TipoMensaje.TAX_MISSING);
            }
        } else {
            msg.mostrarMensaje(JOptionPane.INFORMATION_MESSAGE, 
                    TipoMensaje.EMPTY_TEXT_FIELD);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgTipoImpuesto = new javax.swing.ButtonGroup();
        pnlImpuesto = new javax.swing.JPanel();
        pnlTipoImpuesto = new javax.swing.JPanel();
        rbGeneralVentas = new javax.swing.JRadioButton();
        rbServicio = new javax.swing.JRadioButton();
        rbOtro = new javax.swing.JRadioButton();
        lblTextTarifaImpuesto = new javax.swing.JLabel();
        lblTextMontoImpuesto = new javax.swing.JLabel();
        lblMontoImpuesto = new javax.swing.JLabel();
        btnCancelarImpuesto = new javax.swing.JButton();
        btnAceptarImpuesto = new javax.swing.JButton();
        btnExonerarImpuesto = new javax.swing.JButton();
        txtImpuesto = new javax.swing.JTextField();
        lblTextMontoImpuesto1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar impuesto");

        pnlTipoImpuesto.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de impuesto:"));

        bgTipoImpuesto.add(rbGeneralVentas);
        rbGeneralVentas.setText("General sobre ventas");

        bgTipoImpuesto.add(rbServicio);
        rbServicio.setText("Servicio");

        bgTipoImpuesto.add(rbOtro);
        rbOtro.setSelected(true);
        rbOtro.setText("Otros");

        javax.swing.GroupLayout pnlTipoImpuestoLayout = new javax.swing.GroupLayout(pnlTipoImpuesto);
        pnlTipoImpuesto.setLayout(pnlTipoImpuestoLayout);
        pnlTipoImpuestoLayout.setHorizontalGroup(
            pnlTipoImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTipoImpuestoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlTipoImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbOtro)
                    .addComponent(rbServicio)
                    .addComponent(rbGeneralVentas)))
        );
        pnlTipoImpuestoLayout.setVerticalGroup(
            pnlTipoImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTipoImpuestoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbGeneralVentas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbServicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbOtro)
                .addGap(26, 26, 26))
        );

        lblTextTarifaImpuesto.setText("Impuesto: ");

        lblTextMontoImpuesto.setText("Monto:");

        lblMontoImpuesto.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.activeCaption));

        btnCancelarImpuesto.setText("Cancelar");
        btnCancelarImpuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarImpuestoActionPerformed(evt);
            }
        });

        btnAceptarImpuesto.setText("Aceptar");
        btnAceptarImpuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarImpuestoActionPerformed(evt);
            }
        });

        btnExonerarImpuesto.setText("Exonerar");
        btnExonerarImpuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExonerarImpuestoActionPerformed(evt);
            }
        });

        txtImpuesto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtImpuestoKeyReleased(evt);
            }
        });

        lblTextMontoImpuesto1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTextMontoImpuesto1.setText("%");

        javax.swing.GroupLayout pnlImpuestoLayout = new javax.swing.GroupLayout(pnlImpuesto);
        pnlImpuesto.setLayout(pnlImpuestoLayout);
        pnlImpuestoLayout.setHorizontalGroup(
            pnlImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImpuestoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlTipoImpuesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelarImpuesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(pnlImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAceptarImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExonerarImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlImpuestoLayout.createSequentialGroup()
                        .addGroup(pnlImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTextTarifaImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTextMontoImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMontoImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlImpuestoLayout.createSequentialGroup()
                                .addComponent(txtImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTextMontoImpuesto1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(14, 14, 14))
        );
        pnlImpuestoLayout.setVerticalGroup(
            pnlImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImpuestoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlImpuestoLayout.createSequentialGroup()
                        .addGroup(pnlImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTextTarifaImpuesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTextMontoImpuesto1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTextMontoImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMontoImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(btnExonerarImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addComponent(pnlTipoImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 121, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptarImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlImpuesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlImpuesto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarImpuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarImpuestoActionPerformed
        
        this.dispose();
    }//GEN-LAST:event_btnCancelarImpuestoActionPerformed

    private void btnAceptarImpuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarImpuestoActionPerformed
        enviarDatos();
    }//GEN-LAST:event_btnAceptarImpuestoActionPerformed

    private void btnExonerarImpuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExonerarImpuestoActionPerformed
        enviarDatos();
        dialogExoneracion = new DlgFacExoneracion(this, true);
        dialogExoneracion.setVisible(true);
    }//GEN-LAST:event_btnExonerarImpuestoActionPerformed

    private void txtImpuestoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImpuestoKeyReleased
        //String porcentaje = txtImpuesto.getText();
        double valor = 0;
        try {
            valor = getValorImpuesto();
        } catch (NumberFormatException ex) {
            msg.mostrarMensaje(JOptionPane.INFORMATION_MESSAGE, TipoMensaje.WRONG_DECIMAL_NUMBER);
            System.out.println("Number exception: " + ex);
        }
        lblMontoImpuesto.setText(String.valueOf(valor));
    }//GEN-LAST:event_txtImpuestoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgFacImpuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgFacImpuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgFacImpuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgFacImpuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgFacImpuesto dialog = new DlgFacImpuesto(ifrmFacturacion, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgTipoImpuesto;
    private javax.swing.JButton btnAceptarImpuesto;
    private javax.swing.JButton btnCancelarImpuesto;
    private javax.swing.JButton btnExonerarImpuesto;
    private javax.swing.JLabel lblMontoImpuesto;
    private javax.swing.JLabel lblTextMontoImpuesto;
    private javax.swing.JLabel lblTextMontoImpuesto1;
    private javax.swing.JLabel lblTextTarifaImpuesto;
    private javax.swing.JPanel pnlImpuesto;
    private javax.swing.JPanel pnlTipoImpuesto;
    private javax.swing.JRadioButton rbGeneralVentas;
    private javax.swing.JRadioButton rbOtro;
    private javax.swing.JRadioButton rbServicio;
    private javax.swing.JTextField txtImpuesto;
    // End of variables declaration//GEN-END:variables
}
