/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import logica.negocio.DlgFacExoneracion;

/**
 *
 * @author aoihanabi
 */
public class DlgFacImpuesto extends javax.swing.JDialog {
    public static ItnFrmFacturacion ifrmFacturacion;
    private static DlgFacExoneracion dialogExoneracion;
    /**
     * Creates new form DlgFacImpuesto.
     * @param parent ventana padre de este Jdialog
     * @param modal establece si la ventana permite acceso a otras mientras
     * está abierta.
     */
    public DlgFacImpuesto(ItnFrmFacturacion parent /*java.awt.Frame parent*/, 
            boolean modal) {
        //super(parent, modal);
        this.ifrmFacturacion = parent;
        this.setModal(modal);
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgTipoImpuesto = new javax.swing.ButtonGroup();
        pnlImpuesto = new javax.swing.JPanel();
        pnlTipoImpuesto = new javax.swing.JPanel();
        rbGeneralVentas = new javax.swing.JRadioButton();
        rbServicio = new javax.swing.JRadioButton();
        rbOtro = new javax.swing.JRadioButton();
        lblTextTarifaImpuesto = new javax.swing.JLabel();
        lblTextMontoImpuesto = new javax.swing.JLabel();
        lblMontoImpuesto = new javax.swing.JLabel();
        ftTarifaImpuesto = new javax.swing.JFormattedTextField();
        btnCancelarImpuesto = new javax.swing.JButton();
        btnAceptarImpuesto = new javax.swing.JButton();
        btnExonerarImpuesto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar impuesto");

        pnlTipoImpuesto.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccione el tipo de impuesto:"));

        bgTipoImpuesto.add(rbGeneralVentas);
        rbGeneralVentas.setText("General sobre ventas");

        bgTipoImpuesto.add(rbServicio);
        rbServicio.setText("Servicio");

        bgTipoImpuesto.add(rbOtro);
        rbOtro.setText("Otros");

        javax.swing.GroupLayout pnlTipoImpuestoLayout = new javax.swing.GroupLayout(pnlTipoImpuesto);
        pnlTipoImpuesto.setLayout(pnlTipoImpuestoLayout);
        pnlTipoImpuestoLayout.setHorizontalGroup(
            pnlTipoImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTipoImpuestoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTipoImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbOtro)
                    .addComponent(rbServicio)
                    .addComponent(rbGeneralVentas))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pnlTipoImpuestoLayout.setVerticalGroup(
            pnlTipoImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTipoImpuestoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbGeneralVentas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbServicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbOtro)
                .addGap(26, 26, 26))
        );

        lblTextTarifaImpuesto.setText("Impuesto: ");

        lblTextMontoImpuesto.setText("Monto:");

        lblMontoImpuesto.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.activeCaption));

        ftTarifaImpuesto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getPercentInstance())));
        ftTarifaImpuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftTarifaImpuestoActionPerformed(evt);
            }
        });
        ftTarifaImpuesto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ftTarifaImpuestoKeyReleased(evt);
            }
        });

        btnCancelarImpuesto.setText("Cancelar");
        btnCancelarImpuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarImpuestoActionPerformed(evt);
            }
        });

        btnAceptarImpuesto.setText("Aceptar");
        btnAceptarImpuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarImpuestoActionPerformed(evt);
            }
        });

        btnExonerarImpuesto.setText("Exonerar");
        btnExonerarImpuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExonerarImpuestoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlImpuestoLayout = new javax.swing.GroupLayout(pnlImpuesto);
        pnlImpuesto.setLayout(pnlImpuestoLayout);
        pnlImpuestoLayout.setHorizontalGroup(
            pnlImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImpuestoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTipoImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnlImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAceptarImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExonerarImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlImpuestoLayout.createSequentialGroup()
                        .addGroup(pnlImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTextTarifaImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTextMontoImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMontoImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftTarifaImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pnlImpuestoLayout.setVerticalGroup(
            pnlImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImpuestoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlImpuestoLayout.createSequentialGroup()
                        .addGroup(pnlImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTextTarifaImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftTarifaImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTextMontoImpuesto, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                            .addComponent(lblMontoImpuesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExonerarImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlTipoImpuesto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(pnlImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptarImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlImpuesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlImpuesto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ftTarifaImpuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftTarifaImpuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftTarifaImpuestoActionPerformed

    private void ftTarifaImpuestoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftTarifaImpuestoKeyReleased
        
    }//GEN-LAST:event_ftTarifaImpuestoKeyReleased

    private void btnCancelarImpuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarImpuestoActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarImpuestoActionPerformed

    private void btnAceptarImpuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarImpuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarImpuestoActionPerformed

    private void btnExonerarImpuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExonerarImpuestoActionPerformed
        dialogExoneracion = new DlgFacExoneracion(this, true);
        dialogExoneracion.setVisible(true);
    }//GEN-LAST:event_btnExonerarImpuestoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgFacImpuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgFacImpuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgFacImpuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgFacImpuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgFacImpuesto dialog = new DlgFacImpuesto(ifrmFacturacion, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgTipoImpuesto;
    private javax.swing.JButton btnAceptarImpuesto;
    private javax.swing.JButton btnCancelarImpuesto;
    private javax.swing.JButton btnExonerarImpuesto;
    private javax.swing.JFormattedTextField ftTarifaImpuesto;
    private javax.swing.JLabel lblMontoImpuesto;
    private javax.swing.JLabel lblTextMontoImpuesto;
    private javax.swing.JLabel lblTextTarifaImpuesto;
    private javax.swing.JPanel pnlImpuesto;
    private javax.swing.JPanel pnlTipoImpuesto;
    private javax.swing.JRadioButton rbGeneralVentas;
    private javax.swing.JRadioButton rbOtro;
    private javax.swing.JRadioButton rbServicio;
    // End of variables declaration//GEN-END:variables
}
