/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import controladores.CtrAcceso;
import controladores.CtrMadera;
import java.util.ArrayList;
import logica.negocio.Cliente;
import logica.negocio.Madera;

/**
 * Inicializa la ventana que contiene la información de los productos.
 * @author ahoihanabi
 */
public class ItnFrmInventario extends javax.swing.JInternalFrame {
    private static ItnFrmInventario instancia = null;
    private static CtrMadera controlador;
    private static CtrAcceso sesion;
    private static ArrayList<Madera> productos;
    /**
     * Instancia un nuevo formulario interno de clientes.
     * @param sesionAcc Usuario en sesión actual 
     * @param productos Lista con los productos en la base de datos
     */
    public ItnFrmInventario(CtrAcceso sesionAcc, ArrayList<Madera> productos) {
        initComponents();
        
        //Inicializar variables
        controlador = CtrMadera.getInstancia();
        ItnFrmInventario.productos = productos;
        ItnFrmInventario.sesion = sesionAcc;
        
        pnlCrearMedidasTroza.setVisible(false);
    }
    
    /**
     * Retorna la única instancia de la clase.
     *
     * @param sesionAcc Usuario en sesión actual.
     * @param productos Lista de productos en la base de datos.
     * @return instancia.
     */
    public static ItnFrmInventario getInstancia(CtrAcceso sesionAcc,
            ArrayList<Madera> productos) {
        if (instancia == null) {
            instancia = new ItnFrmInventario(sesionAcc, productos);
        }
        return instancia;
    }
    
    private void cambiarPanelMedidas() {
        int indiceTipoProducto = cmbCrearTipoProducto.getSelectedIndex();
        switch (indiceTipoProducto) {
            case 1:
                pnlCrearMedidasAcerrada.setVisible(false);
                pnlCrearMedidasTroza.setVisible(true);
                pnlCrearMedidasTroza.setBounds(25, 160, 290, 74);
                pnl_agregar.add(pnlCrearMedidasTroza);
                txtCrearPrecioVara.setEnabled(false);
                txtCrearPrecioVara.setText("0");
                instancia.pack();
                break;
            case 2:
                pnlCrearMedidasTroza.setVisible(false);
                pnlCrearMedidasAcerrada.setVisible(true);
                pnlCrearMedidasAcerrada.setBounds(25, 160, 290, 74);
                pnl_agregar.add(pnlCrearMedidasAcerrada);
                txtCrearPrecioVara.setEnabled(true);
                txtCrearPrecioVara.setText("");
                instancia.pack();
                break;
            default:
                pnlCrearMedidasAcerrada.setVisible(false);
                pnlCrearMedidasTroza.setVisible(false);
                txtCrearPrecioVara.setEnabled(true);
                txtCrearPrecioVara.setText("");
                break;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCrearMedidasAcerrada = new javax.swing.JPanel();
        lbl_crear_apellidoCliente8 = new javax.swing.JLabel();
        txt_crear_nombreCliente5 = new javax.swing.JTextField();
        lbl_crear_apellidoCliente9 = new javax.swing.JLabel();
        txt_crear_nombreCliente6 = new javax.swing.JTextField();
        lbl_crear_apellidoCliente10 = new javax.swing.JLabel();
        lbl_crear_apellidoCliente11 = new javax.swing.JLabel();
        txt_crear_nombreCliente7 = new javax.swing.JTextField();
        lbl_crear_apellidoCliente12 = new javax.swing.JLabel();
        pnlCrearMedidasTroza = new javax.swing.JPanel();
        txtCrearCodigoProducto1 = new javax.swing.JTextField();
        lblCrearCodigoProducto1 = new javax.swing.JLabel();
        pnl_modInventario = new javax.swing.JPanel();
        tbpnl_modInventario = new javax.swing.JTabbedPane();
        pnl_listado = new javax.swing.JPanel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        lblListadoInventario = new javax.swing.JLabel();
        txtListadoInventario = new javax.swing.JTextField();
        scpnlTblListadoInventario = new javax.swing.JScrollPane();
        tbListadoInventario = new javax.swing.JTable();
        pnl_agregar = new javax.swing.JPanel();
        lblCrearCodigoProducto = new javax.swing.JLabel();
        lblCrearDescripcionProducto = new javax.swing.JLabel();
        lblCrearTipoProducto = new javax.swing.JLabel();
        lblCrearCantidad = new javax.swing.JLabel();
        spnlCrearProductos = new javax.swing.JScrollPane();
        tbl_crear = new javax.swing.JTable();
        btnCrearProducto = new javax.swing.JButton();
        cmbCrearTipoProducto = new javax.swing.JComboBox<>();
        txtCrearCantidad = new javax.swing.JTextField();
        scpnlCrearDescripcion = new javax.swing.JScrollPane();
        txtCrearDescripcionProducto = new javax.swing.JTextField();
        cmbCrearTipoMadera = new javax.swing.JComboBox<>();
        lblCrearTipoMadera = new javax.swing.JLabel();
        lblCrearPrecioVara = new javax.swing.JLabel();
        txtCrearPrecioVara = new javax.swing.JTextField();
        txtCrearCodigoProducto = new javax.swing.JTextField();
        pnlHabilitar = new javax.swing.JPanel();
        lblDeshabSelectInventario = new javax.swing.JLabel();
        tbDeshab = new javax.swing.JTabbedPane();
        scpnlDeshabProducto = new javax.swing.JScrollPane();
        tblProductosActivos = new javax.swing.JTable();
        scpnlHabilitarProducto = new javax.swing.JScrollPane();
        tblProductosInactivos = new javax.swing.JTable();
        pnlDeshabContainer = new javax.swing.JPanel();
        rbDeshabDeshabProducto = new javax.swing.JRadioButton();
        rbDeshabHabilitarProducto = new javax.swing.JRadioButton();
        btn_deshabilitar = new javax.swing.JButton();
        pnl_agregar1 = new javax.swing.JPanel();
        lblCrearCodigoProducto3 = new javax.swing.JLabel();
        lblCrearDescripcionProducto2 = new javax.swing.JLabel();
        lblCrearTipoProducto2 = new javax.swing.JLabel();
        lblCrearCantidad2 = new javax.swing.JLabel();
        spnlCrearProductos2 = new javax.swing.JScrollPane();
        tbl_crear2 = new javax.swing.JTable();
        btnCrearProducto2 = new javax.swing.JButton();
        cmbCrearTipoProducto2 = new javax.swing.JComboBox<>();
        txtCrearCantidad2 = new javax.swing.JTextField();
        scpnlCrearDescripcion1 = new javax.swing.JScrollPane();
        txtCrearDescripcionProducto2 = new javax.swing.JTextField();
        cmbCrearTipoMadera2 = new javax.swing.JComboBox<>();
        lblCrearTipoMadera2 = new javax.swing.JLabel();
        lblCrearPrecioVara2 = new javax.swing.JLabel();
        txtCrearPrecioVara2 = new javax.swing.JTextField();
        txtCrearCodigoProducto3 = new javax.swing.JTextField();

        pnlCrearMedidasAcerrada.setBorder(javax.swing.BorderFactory.createTitledBorder("Medidas:"));

        lbl_crear_apellidoCliente8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_crear_apellidoCliente8.setText("x");
        lbl_crear_apellidoCliente8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_crear_apellidoCliente9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_crear_apellidoCliente9.setText("Alto");
        lbl_crear_apellidoCliente9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_crear_apellidoCliente10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_crear_apellidoCliente10.setText("Ancho");
        lbl_crear_apellidoCliente10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_crear_apellidoCliente11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_crear_apellidoCliente11.setText("x");
        lbl_crear_apellidoCliente11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_crear_apellidoCliente12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_crear_apellidoCliente12.setText("Grueso");
        lbl_crear_apellidoCliente12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlCrearMedidasAcerradaLayout = new javax.swing.GroupLayout(pnlCrearMedidasAcerrada);
        pnlCrearMedidasAcerrada.setLayout(pnlCrearMedidasAcerradaLayout);
        pnlCrearMedidasAcerradaLayout.setHorizontalGroup(
            pnlCrearMedidasAcerradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCrearMedidasAcerradaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCrearMedidasAcerradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_crear_nombreCliente5)
                    .addComponent(lbl_crear_apellidoCliente9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_crear_apellidoCliente8)
                .addGap(26, 26, 26)
                .addGroup(pnlCrearMedidasAcerradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_crear_apellidoCliente10)
                    .addComponent(txt_crear_nombreCliente6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_crear_apellidoCliente11, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCrearMedidasAcerradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_crear_apellidoCliente12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_crear_nombreCliente7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pnlCrearMedidasAcerradaLayout.setVerticalGroup(
            pnlCrearMedidasAcerradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCrearMedidasAcerradaLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(pnlCrearMedidasAcerradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_crear_nombreCliente5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_crear_nombreCliente6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_crear_nombreCliente7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_crear_apellidoCliente11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_crear_apellidoCliente8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCrearMedidasAcerradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_crear_apellidoCliente12)
                    .addComponent(lbl_crear_apellidoCliente10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_crear_apellidoCliente9)))
        );

        pnlCrearMedidasTroza.setBorder(javax.swing.BorderFactory.createTitledBorder("Medidas:"));

        lblCrearCodigoProducto1.setText("Pulgadas:");

        javax.swing.GroupLayout pnlCrearMedidasTrozaLayout = new javax.swing.GroupLayout(pnlCrearMedidasTroza);
        pnlCrearMedidasTroza.setLayout(pnlCrearMedidasTrozaLayout);
        pnlCrearMedidasTrozaLayout.setHorizontalGroup(
            pnlCrearMedidasTrozaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCrearMedidasTrozaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCrearCodigoProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(txtCrearCodigoProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnlCrearMedidasTrozaLayout.setVerticalGroup(
            pnlCrearMedidasTrozaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCrearMedidasTrozaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCrearMedidasTrozaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblCrearCodigoProducto1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCrearCodigoProducto1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        setClosable(true);
        setIconifiable(true);
        setTitle("Módulo de Inventario");

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("₡#,##0.00"))));
        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });

        lblListadoInventario.setText("Buscar producto: ");

        txtListadoInventario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtListadoInventarioKeyReleased(evt);
            }
        });

        tbListadoInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Tipo de Madera", "Medidas", "Tipo de Producto", "Cantidad", "Descripción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scpnlTblListadoInventario.setViewportView(tbListadoInventario);

        javax.swing.GroupLayout pnl_listadoLayout = new javax.swing.GroupLayout(pnl_listado);
        pnl_listado.setLayout(pnl_listadoLayout);
        pnl_listadoLayout.setHorizontalGroup(
            pnl_listadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_listadoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnl_listadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_listadoLayout.createSequentialGroup()
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnl_listadoLayout.createSequentialGroup()
                        .addComponent(lblListadoInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtListadoInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 1017, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scpnlTblListadoInventario))
                .addGap(23, 23, 23))
        );
        pnl_listadoLayout.setVerticalGroup(
            pnl_listadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_listadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_listadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtListadoInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblListadoInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scpnlTblListadoInventario, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        tbpnl_modInventario.addTab("Listado Inventario", pnl_listado);

        lblCrearCodigoProducto.setText("Código:");

        lblCrearDescripcionProducto.setText("Descripción:");

        lblCrearTipoProducto.setText("Tipo de producto:");

        lblCrearCantidad.setText("Cantidad:");

        tbl_crear.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código de Producto", "Nombre", "Tipo de Madera", "Medidas", "Tipo de Producto", "Cantidad", "Descripción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spnlCrearProductos.setViewportView(tbl_crear);

        btnCrearProducto.setText("Agregar Producto");
        btnCrearProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearProductoActionPerformed(evt);
            }
        });

        cmbCrearTipoProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Seleccione un tipo --", "Troza", "Acerrada", "Terminada" }));
        cmbCrearTipoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCrearTipoProductoActionPerformed(evt);
            }
        });

        scpnlCrearDescripcion.setViewportView(txtCrearDescripcionProducto);

        cmbCrearTipoMadera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Seleccione un tipo --", "Cedro", "Amarillón" }));

        lblCrearTipoMadera.setText("Tipo de madera:");

        lblCrearPrecioVara.setText("Precio por vara:");

        javax.swing.GroupLayout pnl_agregarLayout = new javax.swing.GroupLayout(pnl_agregar);
        pnl_agregar.setLayout(pnl_agregarLayout);
        pnl_agregarLayout.setHorizontalGroup(
            pnl_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_agregarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnl_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spnlCrearProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 1146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_agregarLayout.createSequentialGroup()
                        .addGroup(pnl_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblCrearTipoProducto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbCrearTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCrearCodigoProducto)
                            .addComponent(txtCrearCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(108, 108, 108)
                        .addGroup(pnl_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCrearPrecioVara, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnl_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnl_agregarLayout.createSequentialGroup()
                                    .addGroup(pnl_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCrearCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblCrearTipoMadera, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmbCrearTipoMadera, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblCrearCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(pnl_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblCrearDescripcionProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(scpnlCrearDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnCrearProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(pnl_agregarLayout.createSequentialGroup()
                                    .addComponent(lblCrearPrecioVara, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pnl_agregarLayout.setVerticalGroup(
            pnl_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_agregarLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(pnl_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_agregarLayout.createSequentialGroup()
                        .addComponent(lblCrearDescripcionProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scpnlCrearDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCrearProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_agregarLayout.createSequentialGroup()
                        .addGroup(pnl_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_agregarLayout.createSequentialGroup()
                                .addComponent(lblCrearTipoMadera, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(cmbCrearTipoMadera, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCrearCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCrearCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(pnl_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCrearCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCrearCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnl_agregarLayout.createSequentialGroup()
                                .addComponent(lblCrearTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(cmbCrearTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCrearPrecioVara, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCrearPrecioVara, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(spnlCrearProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        tbpnl_modInventario.addTab("Agregar producto", pnl_agregar);

        lblDeshabSelectInventario.setText("Seleccionar Producto:");

        tblProductosActivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código de Producto", "Nombre", "Tipo de Madera", "Medidas", "Tipo de Producto", "Cantidad", "Descripción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProductosActivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosActivosMouseClicked(evt);
            }
        });
        tblProductosActivos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblProductosActivosKeyReleased(evt);
            }
        });
        scpnlDeshabProducto.setViewportView(tblProductosActivos);

        tbDeshab.addTab("Activos", scpnlDeshabProducto);

        tblProductosInactivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código de Producto", "Nombre", "Tipo de Madera", "Medidas", "Tipo de Producto", "Cantidad", "Descripción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProductosInactivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosInactivosMouseClicked(evt);
            }
        });
        tblProductosInactivos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblProductosInactivosKeyReleased(evt);
            }
        });
        scpnlHabilitarProducto.setViewportView(tblProductosInactivos);

        tbDeshab.addTab("Inactivos", scpnlHabilitarProducto);

        pnlDeshabContainer.setBorder(javax.swing.BorderFactory.createTitledBorder("Activo:"));

        rbDeshabDeshabProducto.setText("Deshabilitar");

        rbDeshabHabilitarProducto.setText("Habilitar");

        javax.swing.GroupLayout pnlDeshabContainerLayout = new javax.swing.GroupLayout(pnlDeshabContainer);
        pnlDeshabContainer.setLayout(pnlDeshabContainerLayout);
        pnlDeshabContainerLayout.setHorizontalGroup(
            pnlDeshabContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeshabContainerLayout.createSequentialGroup()
                .addComponent(rbDeshabHabilitarProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(rbDeshabDeshabProducto)
                .addContainerGap())
        );
        pnlDeshabContainerLayout.setVerticalGroup(
            pnlDeshabContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeshabContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlDeshabContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbDeshabHabilitarProducto)
                    .addComponent(rbDeshabDeshabProducto)))
        );

        btn_deshabilitar.setText("Guardar Cambios");
        btn_deshabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deshabilitarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlHabilitarLayout = new javax.swing.GroupLayout(pnlHabilitar);
        pnlHabilitar.setLayout(pnlHabilitarLayout);
        pnlHabilitarLayout.setHorizontalGroup(
            pnlHabilitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHabilitarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlHabilitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDeshabSelectInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlHabilitarLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(pnlDeshabContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(654, 654, 654)
                        .addComponent(btn_deshabilitar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tbDeshab, javax.swing.GroupLayout.PREFERRED_SIZE, 1144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        pnlHabilitarLayout.setVerticalGroup(
            pnlHabilitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHabilitarLayout.createSequentialGroup()
                .addGroup(pnlHabilitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlHabilitarLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_deshabilitar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlHabilitarLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblDeshabSelectInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbDeshab, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlDeshabContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );

        tbpnl_modInventario.addTab("Habilitar inventario", pnlHabilitar);

        lblCrearCodigoProducto3.setText("Código:");

        lblCrearDescripcionProducto2.setText("Descripción:");

        lblCrearTipoProducto2.setText("Tipo de producto:");

        lblCrearCantidad2.setText("Cantidad:");

        tbl_crear2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código de Producto", "Nombre", "Tipo de Madera", "Medidas", "Tipo de Producto", "Cantidad", "Descripción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spnlCrearProductos2.setViewportView(tbl_crear2);

        btnCrearProducto2.setText("Agregar Producto");
        btnCrearProducto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearProducto2ActionPerformed(evt);
            }
        });

        cmbCrearTipoProducto2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Seleccione un tipo --", "Troza", "Acerrada", "Terminada" }));
        cmbCrearTipoProducto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCrearTipoProducto2ActionPerformed(evt);
            }
        });

        scpnlCrearDescripcion1.setViewportView(txtCrearDescripcionProducto2);

        cmbCrearTipoMadera2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Seleccione un tipo --", "Cedro", "Amarillón" }));

        lblCrearTipoMadera2.setText("Tipo de madera:");

        lblCrearPrecioVara2.setText("Precio por vara:");

        javax.swing.GroupLayout pnl_agregar1Layout = new javax.swing.GroupLayout(pnl_agregar1);
        pnl_agregar1.setLayout(pnl_agregar1Layout);
        pnl_agregar1Layout.setHorizontalGroup(
            pnl_agregar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_agregar1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnl_agregar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spnlCrearProductos2, javax.swing.GroupLayout.PREFERRED_SIZE, 1146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_agregar1Layout.createSequentialGroup()
                        .addGroup(pnl_agregar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_agregar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblCrearTipoProducto2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbCrearTipoProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCrearCodigoProducto3)
                            .addComponent(txtCrearCodigoProducto3, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(108, 108, 108)
                        .addGroup(pnl_agregar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCrearPrecioVara2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnl_agregar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnl_agregar1Layout.createSequentialGroup()
                                    .addGroup(pnl_agregar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCrearCantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblCrearTipoMadera2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmbCrearTipoMadera2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblCrearCantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(pnl_agregar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblCrearDescripcionProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(scpnlCrearDescripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnCrearProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(pnl_agregar1Layout.createSequentialGroup()
                                    .addComponent(lblCrearPrecioVara2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pnl_agregar1Layout.setVerticalGroup(
            pnl_agregar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_agregar1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(pnl_agregar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_agregar1Layout.createSequentialGroup()
                        .addComponent(lblCrearDescripcionProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scpnlCrearDescripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCrearProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_agregar1Layout.createSequentialGroup()
                        .addGroup(pnl_agregar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_agregar1Layout.createSequentialGroup()
                                .addComponent(lblCrearTipoMadera2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(cmbCrearTipoMadera2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl_agregar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCrearCantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCrearCodigoProducto3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(pnl_agregar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCrearCantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCrearCodigoProducto3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnl_agregar1Layout.createSequentialGroup()
                                .addComponent(lblCrearTipoProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(cmbCrearTipoProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCrearPrecioVara2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCrearPrecioVara2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(spnlCrearProductos2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        tbpnl_modInventario.addTab("Editar producto", pnl_agregar1);

        javax.swing.GroupLayout pnl_modInventarioLayout = new javax.swing.GroupLayout(pnl_modInventario);
        pnl_modInventario.setLayout(pnl_modInventarioLayout);
        pnl_modInventarioLayout.setHorizontalGroup(
            pnl_modInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_modInventarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tbpnl_modInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(303, 303, 303))
        );
        pnl_modInventarioLayout.setVerticalGroup(
            pnl_modInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_modInventarioLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(tbpnl_modInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_modInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 1230, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_modInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_deshabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deshabilitarActionPerformed
        //        try {
            //            model = (DefaultTableModel) tbl_deshabilitar.getModel();
            //            int selectedRowIndex = tbl_deshabilitar.getSelectedRow();
            //            String codigo = String.valueOf(model.getValueAt(selectedRowIndex, 0));
            //            Estado estado
            //            = rb_deshab_habilitar.isSelected() ? Estado.Activo : Estado.Deshabilitado;
            //
            //            controlador.actualizarUsuario(
                //                String.valueOf(model.getValueAt(selectedRowIndex, 1)),
                //                String.valueOf(model.getValueAt(selectedRowIndex, 2)),
                //                String.valueOf(model.getValueAt(selectedRowIndex, 3)),
                //                Rol.Administrador, estado, codigo);
            //            //Actualizar
            //            cargarTablas();
            //        } catch (Exception e) {
            //            msg.mostrarMensaje(JOptionPane.INFORMATION_MESSAGE,
                //                TipoMensaje.ANY_ROW_SELECTED);
            //        }
    }//GEN-LAST:event_btn_deshabilitarActionPerformed

    private void tblProductosInactivosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblProductosInactivosKeyReleased
        //        try {
            //            if (evt.getKeyCode() == 38 || evt.getKeyCode() == 40) {
                //                model = (DefaultTableModel) tblClientesInactivos.getModel();
                //                int selectedRowIndex = tblClientesInactivos.getSelectedRow();
                //                String nombre
                //                = String.valueOf(model.getValueAt(selectedRowIndex, 0).toString());
                //
                //                for (int i = 0; i < usuarios.size(); i++) {
                    //                    if (usuarios.get(i).getNombre().equals(nombre)) {
                        //                        if (usuarios.get(i).getEstado().equals(Estado.Deshabilitado)) {
                            //                            rbDeshabHabilitarCliente.setSelected(true);
                            //                        } else {
                            //                            rbDeshabDeshabCliente.setSelected(true);
                            //                        }
                        //                    }
                    //                }
                //            }
            //        } catch (Exception ex) {
            //
            //        }
    }//GEN-LAST:event_tblProductosInactivosKeyReleased

    private void tblProductosInactivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosInactivosMouseClicked
        //        try {
            //            model = (DefaultTableModel) tblClientesInactivos.getModel();
            //            int selectedRowIndex = tblClientesInactivos.getSelectedRow();
            //            String nombre
            //            = String.valueOf(model.getValueAt(selectedRowIndex, 0).toString());
            //
            //            for (int i = 0; i < usuarios.size(); i++) {
                //                if (usuarios.get(i).getNombre().equals(nombre)) {
                    //                    //Si el codigo coincide
                    //                    if (usuarios.get(i).getEstado().equals(Estado.Deshabilitado)) {
                        //                        //Verifica el tipo de estado
                        //                        rbDeshabHabilitarCliente.setSelected(true);
                        //                    } else {
                        //                        rbDeshabDeshabCliente.setSelected(true);
                        //                    }
                    //                }
                //            }
            //        } catch (Exception ex) {
            //
            //        }
    }//GEN-LAST:event_tblProductosInactivosMouseClicked

    private void tblProductosActivosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblProductosActivosKeyReleased
        //        try {
            //            if (evt.getKeyCode() == 38 || evt.getKeyCode() == 40) {
                //                model = (DefaultTableModel) tblClientesActivos.getModel();
                //                int selectedRowIndex = tblClientesActivos.getSelectedRow();
                //                String nombre
                //                = String.valueOf(model.getValueAt(selectedRowIndex, 0).toString());
                //
                //                for (int i = 0; i < usuarios.size(); i++) {
                    //                    if (usuarios.get(i).getNombre().equals(nombre)) {
                        //                        //Si el codigo coincide
                        //                        if (usuarios.get(i).getEstado().equals(Estado.Activo)) {
                            //                            //Verifica el tipo de estado
                            //                            rbDeshabDeshabCliente.setSelected(true);
                            //                        } else {
                            //                            rbDeshabHabilitarCliente.setSelected(true);
                            //                        }
                        //                    }
                    //                }
                //            }
            //        } catch (Exception ex) {
            //
            //        }
    }//GEN-LAST:event_tblProductosActivosKeyReleased

    private void tblProductosActivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosActivosMouseClicked
        //        try {
            //            model = (DefaultTableModel) tblClientesActivos.getModel();
            //            int selectedRowIndex = tblClientesActivos.getSelectedRow();
            //            String nombre
            //            = String.valueOf(model.getValueAt(selectedRowIndex, 0).toString());
            //
            //            for (int i = 0; i < usuarios.size(); i++) {
                //                if (usuarios.get(i).getNombre().equals(nombre)) {
                    //                    //Si el codigo coincide
                    //                    if (usuarios.get(i).getEstado().equals(Estado.Activo)) {
                        //                        //Verifica el tipo de estado
                        //                        rbDeshabDeshabCliente.setSelected(true);
                        //                    } else {
                        //                        rbDeshabHabilitarCliente.setSelected(true);
                        //                    }
                    //                }
                //            }
            //        } catch (Exception ex) {
            //
            //        }
    }//GEN-LAST:event_tblProductosActivosMouseClicked

    private void cmbCrearTipoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCrearTipoProductoActionPerformed
        cambiarPanelMedidas();
        
    }//GEN-LAST:event_cmbCrearTipoProductoActionPerformed

    private void btnCrearProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearProductoActionPerformed

    }//GEN-LAST:event_btnCrearProductoActionPerformed

    private void txtListadoInventarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtListadoInventarioKeyReleased

    }//GEN-LAST:event_txtListadoInventarioKeyReleased

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void btnCrearProducto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearProducto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearProducto2ActionPerformed

    private void cmbCrearTipoProducto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCrearTipoProducto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCrearTipoProducto2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearProducto;
    private javax.swing.JButton btnCrearProducto2;
    private javax.swing.JButton btn_deshabilitar;
    private javax.swing.JComboBox<String> cmbCrearTipoMadera;
    private javax.swing.JComboBox<String> cmbCrearTipoMadera2;
    private javax.swing.JComboBox<String> cmbCrearTipoProducto;
    private javax.swing.JComboBox<String> cmbCrearTipoProducto2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel lblCrearCantidad;
    private javax.swing.JLabel lblCrearCantidad2;
    private javax.swing.JLabel lblCrearCodigoProducto;
    private javax.swing.JLabel lblCrearCodigoProducto1;
    private javax.swing.JLabel lblCrearCodigoProducto3;
    private javax.swing.JLabel lblCrearDescripcionProducto;
    private javax.swing.JLabel lblCrearDescripcionProducto2;
    private javax.swing.JLabel lblCrearPrecioVara;
    private javax.swing.JLabel lblCrearPrecioVara2;
    private javax.swing.JLabel lblCrearTipoMadera;
    private javax.swing.JLabel lblCrearTipoMadera2;
    private javax.swing.JLabel lblCrearTipoProducto;
    private javax.swing.JLabel lblCrearTipoProducto2;
    private javax.swing.JLabel lblDeshabSelectInventario;
    private javax.swing.JLabel lblListadoInventario;
    private javax.swing.JLabel lbl_crear_apellidoCliente10;
    private javax.swing.JLabel lbl_crear_apellidoCliente11;
    private javax.swing.JLabel lbl_crear_apellidoCliente12;
    private javax.swing.JLabel lbl_crear_apellidoCliente8;
    private javax.swing.JLabel lbl_crear_apellidoCliente9;
    private javax.swing.JPanel pnlCrearMedidasAcerrada;
    private javax.swing.JPanel pnlCrearMedidasTroza;
    private javax.swing.JPanel pnlDeshabContainer;
    private javax.swing.JPanel pnlHabilitar;
    private javax.swing.JPanel pnl_agregar;
    private javax.swing.JPanel pnl_agregar1;
    private javax.swing.JPanel pnl_listado;
    private javax.swing.JPanel pnl_modInventario;
    private javax.swing.JRadioButton rbDeshabDeshabProducto;
    private javax.swing.JRadioButton rbDeshabHabilitarProducto;
    private javax.swing.JScrollPane scpnlCrearDescripcion;
    private javax.swing.JScrollPane scpnlCrearDescripcion1;
    private javax.swing.JScrollPane scpnlDeshabProducto;
    private javax.swing.JScrollPane scpnlHabilitarProducto;
    private javax.swing.JScrollPane scpnlTblListadoInventario;
    private javax.swing.JScrollPane spnlCrearProductos;
    private javax.swing.JScrollPane spnlCrearProductos2;
    private javax.swing.JTabbedPane tbDeshab;
    private javax.swing.JTable tbListadoInventario;
    private javax.swing.JTable tblProductosActivos;
    private javax.swing.JTable tblProductosInactivos;
    private javax.swing.JTable tbl_crear;
    private javax.swing.JTable tbl_crear2;
    private javax.swing.JTabbedPane tbpnl_modInventario;
    private javax.swing.JTextField txtCrearCantidad;
    private javax.swing.JTextField txtCrearCantidad2;
    private javax.swing.JTextField txtCrearCodigoProducto;
    private javax.swing.JTextField txtCrearCodigoProducto1;
    private javax.swing.JTextField txtCrearCodigoProducto3;
    private javax.swing.JTextField txtCrearDescripcionProducto;
    private javax.swing.JTextField txtCrearDescripcionProducto2;
    private javax.swing.JTextField txtCrearPrecioVara;
    private javax.swing.JTextField txtCrearPrecioVara2;
    private javax.swing.JTextField txtListadoInventario;
    private javax.swing.JTextField txt_crear_nombreCliente5;
    private javax.swing.JTextField txt_crear_nombreCliente6;
    private javax.swing.JTextField txt_crear_nombreCliente7;
    // End of variables declaration//GEN-END:variables

    
}
