/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import controladores.CtrAcceso;
import controladores.CtrMadera;
import java.util.ArrayList;
import logica.negocio.Cliente;
import logica.negocio.Madera;

/**
 * Inicializa la ventana que contiene la información de los productos.
 * @author ahoihanabi
 */
public class ItnFrmInventario extends javax.swing.JInternalFrame {
    private static ItnFrmInventario instancia = null;
    private static CtrMadera controlador;
    private static CtrAcceso sesion;
    private static ArrayList<Madera> productos;
    /**
     * Instancia un nuevo formulario interno de clientes.
     * @param sesionAcc Usuario en sesión actual 
     * @param productos Lista con los productos en la base de datos
     */
    public ItnFrmInventario(CtrAcceso sesionAcc, ArrayList<Madera> productos) {
        initComponents();
        
        //Inicializar variables
        controlador = CtrMadera.getInstancia();
        ItnFrmInventario.productos = productos;
        ItnFrmInventario.sesion = sesionAcc;
    }
    
    /**
     * Retorna la única instancia de la clase.
     *
     * @param sesionAcc Usuario en sesión actual.
     * @param productos Lista de productos en la base de datos.
     * @return instancia.
     */
    public static ItnFrmInventario getInstancia(CtrAcceso sesionAcc,
            ArrayList<Madera> productos) {
        if (instancia == null) {
            instancia = new ItnFrmInventario(sesionAcc, productos);
        }
        return instancia;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_modInventario = new javax.swing.JPanel();
        tbpnl_modInventario = new javax.swing.JTabbedPane();
        pnl_listado = new javax.swing.JPanel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        lblListadoCliente = new javax.swing.JLabel();
        txtListadoCliente = new javax.swing.JTextField();
        scpnlTblListadoCliente = new javax.swing.JScrollPane();
        tbListadoCliente = new javax.swing.JTable();
        pnl_agregar = new javax.swing.JPanel();
        lbl_crear_nombreProducto = new javax.swing.JLabel();
        lbl_crear_cedulaCliente = new javax.swing.JLabel();
        lbl_crear_apellidoCliente1 = new javax.swing.JLabel();
        lbl_crear_limiteCliente = new javax.swing.JLabel();
        spnl_crear_clientes = new javax.swing.JScrollPane();
        tbl_crear = new javax.swing.JTable();
        btnCrearCliente = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        txt_crear_telefono1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_crear_telefono2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        txt_crear_nombreCliente2 = new javax.swing.JTextField();
        lbl_crear_apellidoCliente6 = new javax.swing.JLabel();
        txt_crear_nombreCliente3 = new javax.swing.JTextField();
        lbl_crear_apellidoCliente3 = new javax.swing.JLabel();
        lbl_crear_apellidoCliente5 = new javax.swing.JLabel();
        lbl_crear_apellidoCliente7 = new javax.swing.JLabel();
        txt_crear_nombreCliente4 = new javax.swing.JTextField();
        lbl_crear_apellidoCliente4 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        lbl_crear_apellidoCliente16 = new javax.swing.JLabel();
        lbl_crear_limiteCliente1 = new javax.swing.JLabel();
        txt_crear_telefono3 = new javax.swing.JTextField();
        txtCrearCodigoArticulo = new javax.swing.JTextField();
        pnl_actualizar = new javax.swing.JPanel();
        lbl_crear_nombreProducto2 = new javax.swing.JLabel();
        lbl_crear_cedulaCliente1 = new javax.swing.JLabel();
        lbl_crear_apellidoCliente8 = new javax.swing.JLabel();
        lbl_crear_apellidoCliente9 = new javax.swing.JLabel();
        txt_crear_nombreCliente5 = new javax.swing.JTextField();
        spnl_crear_clientes1 = new javax.swing.JScrollPane();
        tbl_crear1 = new javax.swing.JTable();
        btnCrearCliente1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        lbl_crear_apellidoCliente10 = new javax.swing.JLabel();
        txt_crear_nombreCliente6 = new javax.swing.JTextField();
        txt_crear_nombreCliente7 = new javax.swing.JTextField();
        lbl_crear_apellidoCliente11 = new javax.swing.JLabel();
        lbl_crear_apellidoCliente12 = new javax.swing.JLabel();
        lbl_crear_apellidoCliente13 = new javax.swing.JLabel();
        lbl_crear_apellidoCliente14 = new javax.swing.JLabel();
        lbl_crear_nombreProducto3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_crear_telefono4 = new javax.swing.JTextField();
        lbl_crear_apellidoCliente15 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        pnlHabilitar = new javax.swing.JPanel();
        lblDeshabSelectUsuario = new javax.swing.JLabel();
        tbDeshab = new javax.swing.JTabbedPane();
        scpnlClientesDeshab = new javax.swing.JScrollPane();
        tblClientesActivos = new javax.swing.JTable();
        scpnlClientesHabilitar = new javax.swing.JScrollPane();
        tblClientesInactivos = new javax.swing.JTable();
        pnlDeshabContainer = new javax.swing.JPanel();
        rbDeshabDeshabCliente = new javax.swing.JRadioButton();
        rbDeshabHabilitarCliente = new javax.swing.JRadioButton();
        btn_deshabilitar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Módulo de Inventario");

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("₡#,##0.00"))));
        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });

        lblListadoCliente.setText("Buscar producto: ");

        txtListadoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtListadoClienteKeyReleased(evt);
            }
        });

        tbListadoCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cédula", "Primer Apellido", "Segundo Apellido", "Nombre", "Crédito", "Límite de crédito", "Contactos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scpnlTblListadoCliente.setViewportView(tbListadoCliente);

        javax.swing.GroupLayout pnl_listadoLayout = new javax.swing.GroupLayout(pnl_listado);
        pnl_listado.setLayout(pnl_listadoLayout);
        pnl_listadoLayout.setHorizontalGroup(
            pnl_listadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_listadoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnl_listadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_listadoLayout.createSequentialGroup()
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnl_listadoLayout.createSequentialGroup()
                        .addComponent(lblListadoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtListadoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 1017, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scpnlTblListadoCliente))
                .addGap(23, 23, 23))
        );
        pnl_listadoLayout.setVerticalGroup(
            pnl_listadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_listadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_listadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtListadoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblListadoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scpnlTblListadoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        tbpnl_modInventario.addTab("Listado Inventario", pnl_listado);

        lbl_crear_nombreProducto.setText("Código:");

        lbl_crear_cedulaCliente.setText("Descripción:");

        lbl_crear_apellidoCliente1.setText("Tipo de producto:");

        lbl_crear_limiteCliente.setText("Cantidad:");

        tbl_crear.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo de Madera", "Medidas", "Cantidad", "Descripción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spnl_crear_clientes.setViewportView(tbl_crear);

        btnCrearCliente.setText("Agregar Producto");
        btnCrearCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearClienteActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acerrada", "Item 2", "Item 3", "Item 4" }));

        jScrollPane1.setViewportView(txt_crear_telefono2);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Medidas"));

        lbl_crear_apellidoCliente6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_crear_apellidoCliente6.setText("Alto");
        lbl_crear_apellidoCliente6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_crear_apellidoCliente3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_crear_apellidoCliente3.setText("x");
        lbl_crear_apellidoCliente3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_crear_apellidoCliente5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_crear_apellidoCliente5.setText("Ancho");
        lbl_crear_apellidoCliente5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_crear_apellidoCliente7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_crear_apellidoCliente7.setText("x");
        lbl_crear_apellidoCliente7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_crear_apellidoCliente4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_crear_apellidoCliente4.setText("Grueso");
        lbl_crear_apellidoCliente4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_crear_nombreCliente2)
                    .addComponent(lbl_crear_apellidoCliente6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_crear_apellidoCliente3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_crear_apellidoCliente5)
                    .addComponent(txt_crear_nombreCliente3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_crear_apellidoCliente7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_crear_apellidoCliente4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_crear_nombreCliente4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_crear_nombreCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_crear_apellidoCliente3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_crear_nombreCliente3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_crear_nombreCliente4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_crear_apellidoCliente7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_crear_apellidoCliente4)
                    .addComponent(lbl_crear_apellidoCliente5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_crear_apellidoCliente6)))
        );

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cedro", "Item 2", "Item 3", "Item 4" }));

        lbl_crear_apellidoCliente16.setText("Tipo de Madera:");

        lbl_crear_limiteCliente1.setText("Precio por vara:");

        javax.swing.GroupLayout pnl_agregarLayout = new javax.swing.GroupLayout(pnl_agregar);
        pnl_agregar.setLayout(pnl_agregarLayout);
        pnl_agregarLayout.setHorizontalGroup(
            pnl_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_agregarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnl_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spnl_crear_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 1146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_agregarLayout.createSequentialGroup()
                        .addGroup(pnl_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl_crear_nombreProducto, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_crear_apellidoCliente1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCrearCodigoArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(108, 108, 108)
                        .addGroup(pnl_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_crear_telefono3, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnl_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnl_agregarLayout.createSequentialGroup()
                                    .addGroup(pnl_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_crear_telefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_crear_apellidoCliente16, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_crear_limiteCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(pnl_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl_crear_cedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnCrearCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(pnl_agregarLayout.createSequentialGroup()
                                    .addComponent(lbl_crear_limiteCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pnl_agregarLayout.setVerticalGroup(
            pnl_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_agregarLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(pnl_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_agregarLayout.createSequentialGroup()
                        .addComponent(lbl_crear_cedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCrearCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_agregarLayout.createSequentialGroup()
                        .addGroup(pnl_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnl_agregarLayout.createSequentialGroup()
                                .addComponent(lbl_crear_nombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCrearCodigoArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_crear_apellidoCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_agregarLayout.createSequentialGroup()
                                .addComponent(lbl_crear_apellidoCliente16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_crear_limiteCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(txt_crear_telefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_agregarLayout.createSequentialGroup()
                                .addComponent(lbl_crear_limiteCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_crear_telefono3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(spnl_crear_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        tbpnl_modInventario.addTab("Agregar producto", pnl_agregar);

        lbl_crear_nombreProducto2.setText("Nombre:");

        lbl_crear_cedulaCliente1.setText("Descripción:");

        lbl_crear_apellidoCliente8.setText("Tipo de producto:");

        lbl_crear_apellidoCliente9.setText("Medidas producto:");

        tbl_crear1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo de Madera", "Medidas", "Cantidad", "Descripción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spnl_crear_clientes1.setViewportView(tbl_crear1);

        btnCrearCliente1.setText("Crear Cliente");
        btnCrearCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCliente1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cedro", "Item 2", "Item 3", "Item 4" }));

        lbl_crear_apellidoCliente10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_crear_apellidoCliente10.setText("x");
        lbl_crear_apellidoCliente10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_crear_apellidoCliente11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_crear_apellidoCliente11.setText("Grueso");
        lbl_crear_apellidoCliente11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_crear_apellidoCliente12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_crear_apellidoCliente12.setText("Ancho");
        lbl_crear_apellidoCliente12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_crear_apellidoCliente13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_crear_apellidoCliente13.setText("Alto");
        lbl_crear_apellidoCliente13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_crear_apellidoCliente14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_crear_apellidoCliente14.setText("x");
        lbl_crear_apellidoCliente14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_crear_nombreProducto3.setText("(Medida + Tipo)");
        lbl_crear_nombreProducto3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)));

        jScrollPane2.setViewportView(txt_crear_telefono4);

        lbl_crear_apellidoCliente15.setText("Tipo de producto:");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cedro", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnl_actualizarLayout = new javax.swing.GroupLayout(pnl_actualizar);
        pnl_actualizar.setLayout(pnl_actualizarLayout);
        pnl_actualizarLayout.setHorizontalGroup(
            pnl_actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_actualizarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnl_actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_actualizarLayout.createSequentialGroup()
                        .addGroup(pnl_actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_actualizarLayout.createSequentialGroup()
                                .addGroup(pnl_actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_crear_nombreCliente5)
                                    .addComponent(lbl_crear_apellidoCliente13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_crear_apellidoCliente10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnl_actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_crear_apellidoCliente12)
                                    .addComponent(txt_crear_nombreCliente6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_crear_apellidoCliente14, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnl_actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_crear_apellidoCliente11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_crear_nombreCliente7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbl_crear_apellidoCliente9, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_crear_apellidoCliente15, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnl_actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_crear_apellidoCliente8, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_crear_nombreProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_crear_nombreProducto3, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnl_actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_crear_cedulaCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2)
                            .addComponent(btnCrearCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(spnl_crear_clientes1, javax.swing.GroupLayout.PREFERRED_SIZE, 1146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        pnl_actualizarLayout.setVerticalGroup(
            pnl_actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_actualizarLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pnl_actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_crear_cedulaCliente1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_crear_apellidoCliente8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_crear_apellidoCliente15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnl_actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_actualizarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_crear_nombreProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_crear_apellidoCliente9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_crear_nombreCliente5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_crear_apellidoCliente10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_crear_nombreCliente6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_crear_nombreCliente7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_crear_apellidoCliente14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_crear_nombreProducto3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCrearCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_crear_apellidoCliente11)
                            .addComponent(lbl_crear_apellidoCliente12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_crear_apellidoCliente13)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(spnl_crear_clientes1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        tbpnl_modInventario.addTab("Editar producto existente", pnl_actualizar);

        lblDeshabSelectUsuario.setText("Seleccionar Cliente:");

        tblClientesActivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cédula", "Primer Apellido", "Segundo Apellido", "Nombre", "Crédito", "Límite de Crédiito", "Contacto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblClientesActivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesActivosMouseClicked(evt);
            }
        });
        tblClientesActivos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblClientesActivosKeyReleased(evt);
            }
        });
        scpnlClientesDeshab.setViewportView(tblClientesActivos);

        tbDeshab.addTab("Activos", scpnlClientesDeshab);

        tblClientesInactivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cédula ", "Primer Apellido", "Segundo Apellido", "Nombre", "Crédito", "Límite de crédito", "Contacto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblClientesInactivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesInactivosMouseClicked(evt);
            }
        });
        tblClientesInactivos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblClientesInactivosKeyReleased(evt);
            }
        });
        scpnlClientesHabilitar.setViewportView(tblClientesInactivos);

        tbDeshab.addTab("Inactivos", scpnlClientesHabilitar);

        pnlDeshabContainer.setBorder(javax.swing.BorderFactory.createTitledBorder("Activo:"));

        rbDeshabDeshabCliente.setText("Deshabilitar");

        rbDeshabHabilitarCliente.setText("Habilitar");

        javax.swing.GroupLayout pnlDeshabContainerLayout = new javax.swing.GroupLayout(pnlDeshabContainer);
        pnlDeshabContainer.setLayout(pnlDeshabContainerLayout);
        pnlDeshabContainerLayout.setHorizontalGroup(
            pnlDeshabContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeshabContainerLayout.createSequentialGroup()
                .addComponent(rbDeshabHabilitarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(rbDeshabDeshabCliente)
                .addContainerGap())
        );
        pnlDeshabContainerLayout.setVerticalGroup(
            pnlDeshabContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeshabContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlDeshabContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbDeshabHabilitarCliente)
                    .addComponent(rbDeshabDeshabCliente)))
        );

        btn_deshabilitar.setText("Guardar Cambios");
        btn_deshabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deshabilitarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlHabilitarLayout = new javax.swing.GroupLayout(pnlHabilitar);
        pnlHabilitar.setLayout(pnlHabilitarLayout);
        pnlHabilitarLayout.setHorizontalGroup(
            pnlHabilitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHabilitarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlHabilitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDeshabSelectUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlHabilitarLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(pnlDeshabContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(654, 654, 654)
                        .addComponent(btn_deshabilitar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tbDeshab, javax.swing.GroupLayout.PREFERRED_SIZE, 1144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        pnlHabilitarLayout.setVerticalGroup(
            pnlHabilitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHabilitarLayout.createSequentialGroup()
                .addGroup(pnlHabilitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlHabilitarLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_deshabilitar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlHabilitarLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblDeshabSelectUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbDeshab, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlDeshabContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );

        tbpnl_modInventario.addTab("Habilitar inventario", pnlHabilitar);

        javax.swing.GroupLayout pnl_modInventarioLayout = new javax.swing.GroupLayout(pnl_modInventario);
        pnl_modInventario.setLayout(pnl_modInventarioLayout);
        pnl_modInventarioLayout.setHorizontalGroup(
            pnl_modInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_modInventarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tbpnl_modInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(303, 303, 303))
        );
        pnl_modInventarioLayout.setVerticalGroup(
            pnl_modInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_modInventarioLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(tbpnl_modInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_modInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 1230, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_modInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtListadoClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtListadoClienteKeyReleased
        
    }//GEN-LAST:event_txtListadoClienteKeyReleased

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void btnCrearClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearClienteActionPerformed
       
    }//GEN-LAST:event_btnCrearClienteActionPerformed

    private void tblClientesActivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesActivosMouseClicked
        //        try {
            //            model = (DefaultTableModel) tblClientesActivos.getModel();
            //            int selectedRowIndex = tblClientesActivos.getSelectedRow();
            //            String nombre
            //            = String.valueOf(model.getValueAt(selectedRowIndex, 0).toString());
            //
            //            for (int i = 0; i < usuarios.size(); i++) {
                //                if (usuarios.get(i).getNombre().equals(nombre)) {
                    //                    //Si el codigo coincide
                    //                    if (usuarios.get(i).getEstado().equals(Estado.Activo)) {
                        //                        //Verifica el tipo de estado
                        //                        rbDeshabDeshabCliente.setSelected(true);
                        //                    } else {
                        //                        rbDeshabHabilitarCliente.setSelected(true);
                        //                    }
                    //                }
                //            }
            //        } catch (Exception ex) {
            //
            //        }
    }//GEN-LAST:event_tblClientesActivosMouseClicked

    private void tblClientesActivosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblClientesActivosKeyReleased
        //        try {
            //            if (evt.getKeyCode() == 38 || evt.getKeyCode() == 40) {
                //                model = (DefaultTableModel) tblClientesActivos.getModel();
                //                int selectedRowIndex = tblClientesActivos.getSelectedRow();
                //                String nombre
                //                = String.valueOf(model.getValueAt(selectedRowIndex, 0).toString());
                //
                //                for (int i = 0; i < usuarios.size(); i++) {
                    //                    if (usuarios.get(i).getNombre().equals(nombre)) {
                        //                        //Si el codigo coincide
                        //                        if (usuarios.get(i).getEstado().equals(Estado.Activo)) {
                            //                            //Verifica el tipo de estado
                            //                            rbDeshabDeshabCliente.setSelected(true);
                            //                        } else {
                            //                            rbDeshabHabilitarCliente.setSelected(true);
                            //                        }
                        //                    }
                    //                }
                //            }
            //        } catch (Exception ex) {
            //
            //        }
    }//GEN-LAST:event_tblClientesActivosKeyReleased

    private void tblClientesInactivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesInactivosMouseClicked
        //        try {
            //            model = (DefaultTableModel) tblClientesInactivos.getModel();
            //            int selectedRowIndex = tblClientesInactivos.getSelectedRow();
            //            String nombre
            //            = String.valueOf(model.getValueAt(selectedRowIndex, 0).toString());
            //
            //            for (int i = 0; i < usuarios.size(); i++) {
                //                if (usuarios.get(i).getNombre().equals(nombre)) {
                    //                    //Si el codigo coincide
                    //                    if (usuarios.get(i).getEstado().equals(Estado.Deshabilitado)) {
                        //                        //Verifica el tipo de estado
                        //                        rbDeshabHabilitarCliente.setSelected(true);
                        //                    } else {
                        //                        rbDeshabDeshabCliente.setSelected(true);
                        //                    }
                    //                }
                //            }
            //        } catch (Exception ex) {
            //
            //        }
    }//GEN-LAST:event_tblClientesInactivosMouseClicked

    private void tblClientesInactivosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblClientesInactivosKeyReleased
        //        try {
            //            if (evt.getKeyCode() == 38 || evt.getKeyCode() == 40) {
                //                model = (DefaultTableModel) tblClientesInactivos.getModel();
                //                int selectedRowIndex = tblClientesInactivos.getSelectedRow();
                //                String nombre
                //                = String.valueOf(model.getValueAt(selectedRowIndex, 0).toString());
                //
                //                for (int i = 0; i < usuarios.size(); i++) {
                    //                    if (usuarios.get(i).getNombre().equals(nombre)) {
                        //                        if (usuarios.get(i).getEstado().equals(Estado.Deshabilitado)) {
                            //                            rbDeshabHabilitarCliente.setSelected(true);
                            //                        } else {
                            //                            rbDeshabDeshabCliente.setSelected(true);
                            //                        }
                        //                    }
                    //                }
                //            }
            //        } catch (Exception ex) {
            //
            //        }
    }//GEN-LAST:event_tblClientesInactivosKeyReleased

    private void btn_deshabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deshabilitarActionPerformed
        //        try {
            //            model = (DefaultTableModel) tbl_deshabilitar.getModel();
            //            int selectedRowIndex = tbl_deshabilitar.getSelectedRow();
            //            String codigo = String.valueOf(model.getValueAt(selectedRowIndex, 0));
            //            Estado estado
            //            = rb_deshab_habilitar.isSelected() ? Estado.Activo : Estado.Deshabilitado;
            //
            //            controlador.actualizarUsuario(
                //                String.valueOf(model.getValueAt(selectedRowIndex, 1)),
                //                String.valueOf(model.getValueAt(selectedRowIndex, 2)),
                //                String.valueOf(model.getValueAt(selectedRowIndex, 3)),
                //                Rol.Administrador, estado, codigo);
            //            //Actualizar
            //            cargarTablas();
            //        } catch (Exception e) {
            //            msg.mostrarMensaje(JOptionPane.INFORMATION_MESSAGE,
                //                TipoMensaje.ANY_ROW_SELECTED);
            //        }
    }//GEN-LAST:event_btn_deshabilitarActionPerformed

    private void btnCrearCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearCliente1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearCliente;
    private javax.swing.JButton btnCrearCliente1;
    private javax.swing.JButton btn_deshabilitar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDeshabSelectUsuario;
    private javax.swing.JLabel lblListadoCliente;
    private javax.swing.JLabel lbl_crear_apellidoCliente1;
    private javax.swing.JLabel lbl_crear_apellidoCliente10;
    private javax.swing.JLabel lbl_crear_apellidoCliente11;
    private javax.swing.JLabel lbl_crear_apellidoCliente12;
    private javax.swing.JLabel lbl_crear_apellidoCliente13;
    private javax.swing.JLabel lbl_crear_apellidoCliente14;
    private javax.swing.JLabel lbl_crear_apellidoCliente15;
    private javax.swing.JLabel lbl_crear_apellidoCliente16;
    private javax.swing.JLabel lbl_crear_apellidoCliente3;
    private javax.swing.JLabel lbl_crear_apellidoCliente4;
    private javax.swing.JLabel lbl_crear_apellidoCliente5;
    private javax.swing.JLabel lbl_crear_apellidoCliente6;
    private javax.swing.JLabel lbl_crear_apellidoCliente7;
    private javax.swing.JLabel lbl_crear_apellidoCliente8;
    private javax.swing.JLabel lbl_crear_apellidoCliente9;
    private javax.swing.JLabel lbl_crear_cedulaCliente;
    private javax.swing.JLabel lbl_crear_cedulaCliente1;
    private javax.swing.JLabel lbl_crear_limiteCliente;
    private javax.swing.JLabel lbl_crear_limiteCliente1;
    private javax.swing.JLabel lbl_crear_nombreProducto;
    private javax.swing.JLabel lbl_crear_nombreProducto2;
    private javax.swing.JLabel lbl_crear_nombreProducto3;
    private javax.swing.JPanel pnlDeshabContainer;
    private javax.swing.JPanel pnlHabilitar;
    private javax.swing.JPanel pnl_actualizar;
    private javax.swing.JPanel pnl_agregar;
    private javax.swing.JPanel pnl_listado;
    private javax.swing.JPanel pnl_modInventario;
    private javax.swing.JRadioButton rbDeshabDeshabCliente;
    private javax.swing.JRadioButton rbDeshabHabilitarCliente;
    private javax.swing.JScrollPane scpnlClientesDeshab;
    private javax.swing.JScrollPane scpnlClientesHabilitar;
    private javax.swing.JScrollPane scpnlTblListadoCliente;
    private javax.swing.JScrollPane spnl_crear_clientes;
    private javax.swing.JScrollPane spnl_crear_clientes1;
    private javax.swing.JTabbedPane tbDeshab;
    private javax.swing.JTable tbListadoCliente;
    private javax.swing.JTable tblClientesActivos;
    private javax.swing.JTable tblClientesInactivos;
    private javax.swing.JTable tbl_crear;
    private javax.swing.JTable tbl_crear1;
    private javax.swing.JTabbedPane tbpnl_modInventario;
    private javax.swing.JTextField txtCrearCodigoArticulo;
    private javax.swing.JTextField txtListadoCliente;
    private javax.swing.JTextField txt_crear_nombreCliente2;
    private javax.swing.JTextField txt_crear_nombreCliente3;
    private javax.swing.JTextField txt_crear_nombreCliente4;
    private javax.swing.JTextField txt_crear_nombreCliente5;
    private javax.swing.JTextField txt_crear_nombreCliente6;
    private javax.swing.JTextField txt_crear_nombreCliente7;
    private javax.swing.JTextField txt_crear_telefono1;
    private javax.swing.JTextField txt_crear_telefono2;
    private javax.swing.JTextField txt_crear_telefono3;
    private javax.swing.JTextField txt_crear_telefono4;
    // End of variables declaration//GEN-END:variables
}
