/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package util;

/**
 *
 * @author dark-reaper
 */
public enum MessageHelper {
    ANY_ROW_SELECTED,
    CONFIRMATION_EMAIL_NOT_FOUND,
    CONFIRM_RESET_PASSWORD_CANCEL,
    EMAIL_SYNTAX_FAILURE,
    EMPTY_CONFIRMATION_CODE_FIELD,
    EMPTY_EMAIL_FIELD,
    EMPTY_PASSWORD_FIELD,
    EMPTY_USERNAME_FIELD,
    MISMATCHING_PASSWORD_FIELDS,
    PASSWORD_SYNTAX_FAILURE,
    RESET_PASSWORD_FAILURE,
    RESET_PASSWORD_SUCCESS,
    SEND_CONFIRMATION_EMAIL_FAILURE,
    SEND_CONFIRMATION_EMAIL_SUCCESS,
    USER_INSERTION_FAILURE,
    USER_INSERTION_SUCCESS,
    USER_ACCESS_FAILURE,
    USER_UPDATE_SUCCESS,
    USER_UPDATE_FAILURE,
    USER_ACCESS_SUCCESS,
    USERNAME_SYNTAX_FAILURE,
    WRONG_CONFIRMATION_CODE,
}
